<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 9 Tidyverse | Introducción a Ciencia de Datos con R (Tidyverse)</title>
  <meta name="description" content="Curso de aprendizaje de programación de R para Ciencia de Datos con Tidyverse" />
  <meta name="generator" content="bookdown 0.22 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 9 Tidyverse | Introducción a Ciencia de Datos con R (Tidyverse)" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Curso de aprendizaje de programación de R para Ciencia de Datos con Tidyverse" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 9 Tidyverse | Introducción a Ciencia de Datos con R (Tidyverse)" />
  
  <meta name="twitter:description" content="Curso de aprendizaje de programación de R para Ciencia de Datos con Tidyverse" />
  

<meta name="author" content="Karina Lizette Gamboa Puente" />
<meta name="author" content="Oscar Arturo Bringas López" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="lectura-de-datos.html"/>
<link rel="next" href="ggplot.html"/>
<script src="libs/header-attrs-2.10/header-attrs.js"></script>
<script src="libs/jquery-3.5.1/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />









<link href="libs/anchor-sections-1.0.1/anchor-sections.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.0.1/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/str_view-0.1.0/str_view.css" rel="stylesheet" />
<script src="libs/str_view-binding-1.4.0/str_view.js"></script>
<script src="libs/plotly-binding-4.9.4.1/plotly.js"></script>
<script src="libs/typedarray-0.1/typedarray.min.js"></script>
<link href="libs/crosstalk-1.1.1/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.1.1/js/crosstalk.min.js"></script>
<link href="libs/plotly-htmlwidgets-css-1.57.1/plotly-htmlwidgets.css" rel="stylesheet" />
<script src="libs/plotly-main-1.57.1/plotly-latest.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"><img src="img/amat-logo.png" width="280"></a></li|
|:-:|  
<center>Introducción a Ciencia de Datos con R (Tidyverse)</center>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> BIENVENIDA</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#objetivo"><i class="fa fa-check"></i><b>1.1</b> Objetivo</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#quienes-somos"><i class="fa fa-check"></i><b>1.2</b> ¿Quienes somos?</a></li>
<li class="chapter" data-level="1.3" data-path="index.html"><a href="index.html#ciencia-de-datos-en-r"><i class="fa fa-check"></i><b>1.3</b> Ciencia de Datos en R</a></li>
<li class="chapter" data-level="1.4" data-path="index.html"><a href="index.html#estructura-del-curso-actual"><i class="fa fa-check"></i><b>1.4</b> Estructura del curso actual</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="index.html"><a href="index.html#alcances-del-curso"><i class="fa fa-check"></i><b>1.4.1</b> Alcances del curso</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="index.html"><a href="index.html#duración-y-evaluación-del-curso"><i class="fa fa-check"></i><b>1.5</b> Duración y evaluación del curso</a></li>
<li class="chapter" data-level="1.6" data-path="index.html"><a href="index.html#recursos-y-dinámica-de-clase"><i class="fa fa-check"></i><b>1.6</b> Recursos y dinámica de clase</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="introducción-a-ciencia-de-datos.html"><a href="introducción-a-ciencia-de-datos.html"><i class="fa fa-check"></i><b>2</b> Introducción a Ciencia de Datos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="introducción-a-ciencia-de-datos.html"><a href="introducción-a-ciencia-de-datos.html#qué-es-ciencia-de-datos"><i class="fa fa-check"></i><b>2.1</b> ¿Qué es Ciencia de Datos?</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="introducción-a-ciencia-de-datos.html"><a href="introducción-a-ciencia-de-datos.html#definiendo-conceptos"><i class="fa fa-check"></i><b>2.1.1</b> Definiendo conceptos:</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introducción-a-ciencia-de-datos.html"><a href="introducción-a-ciencia-de-datos.html#objetivo-de-la-ciencia-de-datos"><i class="fa fa-check"></i><b>2.2</b> Objetivo de la Ciencia de Datos</a></li>
<li class="chapter" data-level="2.3" data-path="introducción-a-ciencia-de-datos.html"><a href="introducción-a-ciencia-de-datos.html#qué-se-requiere-para-hacer-ciencia-de-datos"><i class="fa fa-check"></i><b>2.3</b> ¿Qué se requiere para hacer Ciencia de Datos?</a></li>
<li class="chapter" data-level="2.4" data-path="introducción-a-ciencia-de-datos.html"><a href="introducción-a-ciencia-de-datos.html#aplicaciones-de-ciencia-de-datos"><i class="fa fa-check"></i><b>2.4</b> Aplicaciones de Ciencia de Datos</a></li>
<li class="chapter" data-level="2.5" data-path="introducción-a-ciencia-de-datos.html"><a href="introducción-a-ciencia-de-datos.html#tipos-de-aprendizaje"><i class="fa fa-check"></i><b>2.5</b> Tipos de aprendizaje</a>
<ul>
<li class="chapter" data-level="2.5.1" data-path="introducción-a-ciencia-de-datos.html"><a href="introducción-a-ciencia-de-datos.html#aprendizaje-supervisado"><i class="fa fa-check"></i><b>2.5.1</b> Aprendizaje supervisado</a></li>
<li class="chapter" data-level="2.5.2" data-path="introducción-a-ciencia-de-datos.html"><a href="introducción-a-ciencia-de-datos.html#aprendizaje-no-supervisado"><i class="fa fa-check"></i><b>2.5.2</b> Aprendizaje no supervisado</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="r.html"><a href="r.html"><i class="fa fa-check"></i><b>3</b> R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="r.html"><a href="r.html#cómo-obtener-r"><i class="fa fa-check"></i><b>3.1</b> ¿Cómo obtener <em>R</em>?</a></li>
<li class="chapter" data-level="3.2" data-path="r.html"><a href="r.html#qué-es-rstudio"><i class="fa fa-check"></i><b>3.2</b> ¿Qué es RStudio?</a></li>
<li class="chapter" data-level="3.3" data-path="r.html"><a href="r.html#r-como-lenguaje-orientado-a-objetos"><i class="fa fa-check"></i><b>3.3</b> <em>R</em> como lenguaje orientado a objetos</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html"><i class="fa fa-check"></i><b>4</b> Tipos de variables</a>
<ul>
<li class="chapter" data-level="4.1" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#variables"><i class="fa fa-check"></i><b>4.1</b> Variables</a></li>
<li class="chapter" data-level="4.2" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#vectores"><i class="fa fa-check"></i><b>4.2</b> Vectores</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#cómo-extraer-elementos-de-un-vector"><i class="fa fa-check"></i><b>4.2.1</b> Cómo extraer elementos de un vector?</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#matrices"><i class="fa fa-check"></i><b>4.3</b> Matrices</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#cómo-extraer-elementos-de-una-matriz"><i class="fa fa-check"></i><b>4.3.1</b> ¿Cómo extraer elementos de una matriz?</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#arreglos"><i class="fa fa-check"></i><b>4.4</b> Arreglos</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#cómo-extraer-elementos-de-un-arreglo"><i class="fa fa-check"></i><b>4.4.1</b> ¿Cómo extraer elementos de un arreglo?</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#data-frames"><i class="fa fa-check"></i><b>4.5</b> Data Frames</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#cómo-extraer-elementos-de-un-data-frame"><i class="fa fa-check"></i><b>4.5.1</b> ¿Cómo extraer elementos de un data frame?</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#listas"><i class="fa fa-check"></i><b>4.6</b> Listas</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#cómo-extraer-elementos-de-una-lista"><i class="fa fa-check"></i><b>4.6.1</b> ¿Cómo extraer elementos de una lista?</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="tipos-de-variables.html"><a href="tipos-de-variables.html#ejercicios"><i class="fa fa-check"></i><b>4.7</b> Ejercicios</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="estilo.html"><a href="estilo.html"><i class="fa fa-check"></i><b>5</b> Guía de estilo</a>
<ul>
<li class="chapter" data-level="5.1" data-path="estilo.html"><a href="estilo.html#nombres-de-los-archivos"><i class="fa fa-check"></i><b>5.1</b> Nombres de los archivos</a></li>
<li class="chapter" data-level="5.2" data-path="estilo.html"><a href="estilo.html#nombres-de-los-objetos"><i class="fa fa-check"></i><b>5.2</b> Nombres de los objetos</a></li>
<li class="chapter" data-level="5.3" data-path="estilo.html"><a href="estilo.html#longitud-de-una-línea-de-código"><i class="fa fa-check"></i><b>5.3</b> Longitud de una línea de código</a></li>
<li class="chapter" data-level="5.4" data-path="estilo.html"><a href="estilo.html#espacios"><i class="fa fa-check"></i><b>5.4</b> Espacios</a></li>
<li class="chapter" data-level="5.5" data-path="estilo.html"><a href="estilo.html#asignación"><i class="fa fa-check"></i><b>5.5</b> Asignación</a></li>
<li class="chapter" data-level="5.6" data-path="estilo.html"><a href="estilo.html#punto-y-coma"><i class="fa fa-check"></i><b>5.6</b> Punto y coma</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="funbas.html"><a href="funbas.html"><i class="fa fa-check"></i><b>6</b> Funciones básicas de R</a>
<ul>
<li class="chapter" data-level="6.1" data-path="funbas.html"><a href="funbas.html#qué-es-una-función-de-r"><i class="fa fa-check"></i><b>6.1</b> ¿Qué es una función de R?</a></li>
<li class="chapter" data-level="6.2" data-path="funbas.html"><a href="funbas.html#operadores-de-asignación"><i class="fa fa-check"></i><b>6.2</b> Operadores de asignación</a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.3" data-path="funbas.html"><a href="funbas.html#operaciones-básicas"><i class="fa fa-check"></i><b>6.3</b> Operaciones básicas</a></li>
<li class="chapter" data-level="6.4" data-path="funbas.html"><a href="funbas.html#pruebas-lógicas"><i class="fa fa-check"></i><b>6.4</b> Pruebas lógicas</a></li>
<li class="chapter" data-level="6.5" data-path="funbas.html"><a href="funbas.html#operadores-lógicos"><i class="fa fa-check"></i><b>6.5</b> Operadores lógicos</a></li>
<li class="chapter" data-level="6.6" data-path="funbas.html"><a href="funbas.html#funciones-sobre-vectores"><i class="fa fa-check"></i><b>6.6</b> Funciones sobre vectores</a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-1"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.7" data-path="funbas.html"><a href="funbas.html#función-rep"><i class="fa fa-check"></i><b>6.7</b> Función <code>rep</code></a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-2"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.8" data-path="funbas.html"><a href="funbas.html#función-seq"><i class="fa fa-check"></i><b>6.8</b> Función <code>seq</code></a>
<ul>
<li class="chapter" data-level="" data-path="funbas.html"><a href="funbas.html#ejemplo-3"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="6.9" data-path="funbas.html"><a href="funbas.html#ejercicios-1"><i class="fa fa-check"></i><b>6.9</b> EJERCICIOS</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="bucles.html"><a href="bucles.html"><i class="fa fa-check"></i><b>7</b> Instrucciones de control</a>
<ul>
<li class="chapter" data-level="7.1" data-path="bucles.html"><a href="bucles.html#instrucción-if"><i class="fa fa-check"></i><b>7.1</b> Instrucción <code>if</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-4"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="bucles.html"><a href="bucles.html#instrucción-if-else"><i class="fa fa-check"></i><b>7.2</b> Instrucción <code>if</code> <code>else</code></a></li>
<li class="chapter" data-level="7.3" data-path="bucles.html"><a href="bucles.html#instrucción-ifelse"><i class="fa fa-check"></i><b>7.3</b> Instrucción <code>ifelse</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-5"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="bucles.html"><a href="bucles.html#instrucción-for"><i class="fa fa-check"></i><b>7.4</b> Instrucción <code>for</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-6"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="bucles.html"><a href="bucles.html#instrucción-while"><i class="fa fa-check"></i><b>7.5</b> Instrucción <code>while</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-7"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="bucles.html"><a href="bucles.html#instrucción-repeat"><i class="fa fa-check"></i><b>7.6</b> Instrucción <code>repeat</code></a>
<ul>
<li class="chapter" data-level="" data-path="bucles.html"><a href="bucles.html#ejemplo-8"><i class="fa fa-check"></i>Ejemplo</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="lectura-de-datos.html"><a href="lectura-de-datos.html"><i class="fa fa-check"></i><b>8</b> Lectura de datos</a>
<ul>
<li class="chapter" data-level="8.1" data-path="lectura-de-datos.html"><a href="lectura-de-datos.html#lectura-de-datos-1"><i class="fa fa-check"></i><b>8.1</b> Lectura de datos</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="lectura-de-datos.html"><a href="lectura-de-datos.html#archivos-csv"><i class="fa fa-check"></i><b>8.1.1</b> Archivos <em>csv</em></a></li>
<li class="chapter" data-level="8.1.2" data-path="lectura-de-datos.html"><a href="lectura-de-datos.html#archivos-xls-y-xlsx"><i class="fa fa-check"></i><b>8.1.2</b> Archivos <em>xls</em> y <em>xlsx</em></a></li>
<li class="chapter" data-level="8.1.3" data-path="lectura-de-datos.html"><a href="lectura-de-datos.html#archivos-json"><i class="fa fa-check"></i><b>8.1.3</b> Archivos json</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="lectura-de-datos.html"><a href="lectura-de-datos.html#bases-de-datos"><i class="fa fa-check"></i><b>8.2</b> Bases de Datos</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="lectura-de-datos.html"><a href="lectura-de-datos.html#microsoft-sql-server"><i class="fa fa-check"></i><b>8.2.1</b> Microsoft SQL Server</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="tidyverse.html"><a href="tidyverse.html"><i class="fa fa-check"></i><b>9</b> Tidyverse</a>
<ul>
<li class="chapter" data-level="9.1" data-path="tidyverse.html"><a href="tidyverse.html#consultas-de-datos-dplyr"><i class="fa fa-check"></i><b>9.1</b> Consultas de datos (dplyr)</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="tidyverse.html"><a href="tidyverse.html#select"><i class="fa fa-check"></i><b>9.1.1</b> select()</a></li>
<li class="chapter" data-level="9.1.2" data-path="tidyverse.html"><a href="tidyverse.html#filter"><i class="fa fa-check"></i><b>9.1.2</b> filter()</a></li>
<li class="chapter" data-level="9.1.3" data-path="tidyverse.html"><a href="tidyverse.html#arrange"><i class="fa fa-check"></i><b>9.1.3</b> arrange()</a></li>
<li class="chapter" data-level="9.1.4" data-path="tidyverse.html"><a href="tidyverse.html#mutate"><i class="fa fa-check"></i><b>9.1.4</b> mutate()</a></li>
<li class="chapter" data-level="9.1.5" data-path="tidyverse.html"><a href="tidyverse.html#summarise"><i class="fa fa-check"></i><b>9.1.5</b> summarise()</a></li>
<li class="chapter" data-level="9.1.6" data-path="tidyverse.html"><a href="tidyverse.html#group_by"><i class="fa fa-check"></i><b>9.1.6</b> group_by()</a></li>
<li class="chapter" data-level="9.1.7" data-path="tidyverse.html"><a href="tidyverse.html#rowwise"><i class="fa fa-check"></i><b>9.1.7</b> rowwise()</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="tidyverse.html"><a href="tidyverse.html#cruces-de-tablas"><i class="fa fa-check"></i><b>9.2</b> Cruces de tablas</a></li>
<li class="chapter" data-level="9.3" data-path="tidyverse.html"><a href="tidyverse.html#órden-y-reestructuración-de-tablas"><i class="fa fa-check"></i><b>9.3</b> Órden y reestructuración de tablas</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="tidyverse.html"><a href="tidyverse.html#pivote-horizontal"><i class="fa fa-check"></i><b>9.3.1</b> Pivote horizontal</a></li>
<li class="chapter" data-level="9.3.2" data-path="tidyverse.html"><a href="tidyverse.html#pivote-vertical"><i class="fa fa-check"></i><b>9.3.2</b> Pivote vertical</a></li>
<li class="chapter" data-level="9.3.3" data-path="tidyverse.html"><a href="tidyverse.html#unión-de-columnas"><i class="fa fa-check"></i><b>9.3.3</b> Unión de columnas</a></li>
<li class="chapter" data-level="9.3.4" data-path="tidyverse.html"><a href="tidyverse.html#separador-de-columnas"><i class="fa fa-check"></i><b>9.3.4</b> Separador de columnas</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="tidyverse.html"><a href="tidyverse.html#manipulación-de-texto-stringr"><i class="fa fa-check"></i><b>9.4</b> Manipulación de texto (stringr)</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="tidyverse.html"><a href="tidyverse.html#caracteres-especiales"><i class="fa fa-check"></i><b>9.4.1</b> Caracteres especiales</a></li>
<li class="chapter" data-level="9.4.2" data-path="tidyverse.html"><a href="tidyverse.html#tamaño-de-la-cadena"><i class="fa fa-check"></i><b>9.4.2</b> Tamaño de la cadena</a></li>
<li class="chapter" data-level="9.4.3" data-path="tidyverse.html"><a href="tidyverse.html#concatenar-cadenas"><i class="fa fa-check"></i><b>9.4.3</b> Concatenar cadenas</a></li>
<li class="chapter" data-level="9.4.4" data-path="tidyverse.html"><a href="tidyverse.html#extraer-y-reemplazar-subcadenas"><i class="fa fa-check"></i><b>9.4.4</b> Extraer y reemplazar subcadenas</a></li>
<li class="chapter" data-level="9.4.5" data-path="tidyverse.html"><a href="tidyverse.html#expresiones-regulares"><i class="fa fa-check"></i><b>9.4.5</b> Expresiones regulares</a></li>
<li class="chapter" data-level="9.4.6" data-path="tidyverse.html"><a href="tidyverse.html#detectar-coincidencias"><i class="fa fa-check"></i><b>9.4.6</b> Detectar coincidencias</a></li>
<li class="chapter" data-level="9.4.7" data-path="tidyverse.html"><a href="tidyverse.html#contabilizar-coincidencias"><i class="fa fa-check"></i><b>9.4.7</b> Contabilizar coincidencias</a></li>
<li class="chapter" data-level="9.4.8" data-path="tidyverse.html"><a href="tidyverse.html#extraer-coincidencias"><i class="fa fa-check"></i><b>9.4.8</b> Extraer coincidencias</a></li>
<li class="chapter" data-level="9.4.9" data-path="tidyverse.html"><a href="tidyverse.html#reemplazar-coincidencias"><i class="fa fa-check"></i><b>9.4.9</b> Reemplazar coincidencias</a></li>
<li class="chapter" data-level="9.4.10" data-path="tidyverse.html"><a href="tidyverse.html#divisiones-mediante-patrones"><i class="fa fa-check"></i><b>9.4.10</b> Divisiones mediante patrones</a></li>
<li class="chapter" data-level="9.4.11" data-path="tidyverse.html"><a href="tidyverse.html#localización-de-coincidencias"><i class="fa fa-check"></i><b>9.4.11</b> Localización de coincidencias</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="tidyverse.html"><a href="tidyverse.html#manipulación-de-fechas-y-horas"><i class="fa fa-check"></i><b>9.5</b> Manipulación de fechas y horas</a>
<ul>
<li class="chapter" data-level="9.5.1" data-path="tidyverse.html"><a href="tidyverse.html#lectura-y-creación-de-datos-temporales"><i class="fa fa-check"></i><b>9.5.1</b> Lectura y creación de datos temporales</a></li>
<li class="chapter" data-level="9.5.2" data-path="tidyverse.html"><a href="tidyverse.html#extracción-de-datos-temporales"><i class="fa fa-check"></i><b>9.5.2</b> Extracción de datos temporales</a></li>
<li class="chapter" data-level="9.5.3" data-path="tidyverse.html"><a href="tidyverse.html#operaciones-temporales"><i class="fa fa-check"></i><b>9.5.3</b> Operaciones temporales</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="ggplot.html"><a href="ggplot.html"><i class="fa fa-check"></i><b>10</b> Ggplot</a>
<ul>
<li class="chapter" data-level="10.1" data-path="ggplot.html"><a href="ggplot.html#eda-análisis-exploratorio-de-datos"><i class="fa fa-check"></i><b>10.1</b> EDA: Análisis Exploratorio de Datos</a></li>
<li class="chapter" data-level="10.2" data-path="ggplot.html"><a href="ggplot.html#geda-análisis-exploratorio-de-datos-gráficos"><i class="fa fa-check"></i><b>10.2</b> GEDA: Análisis Exploratorio de Datos Gráficos</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="ggplot.html"><a href="ggplot.html#gráficos-univariados"><i class="fa fa-check"></i><b>10.2.1</b> Gráficos univariados:</a></li>
<li class="chapter" data-level="10.2.2" data-path="ggplot.html"><a href="ggplot.html#gráficos-multivariados"><i class="fa fa-check"></i><b>10.2.2</b> Gráficos multivariados</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="ggplot.html"><a href="ggplot.html#ggplot2"><i class="fa fa-check"></i><b>10.3</b> Ggplot2</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="ggplot.html"><a href="ggplot.html#objetos-aesteticos"><i class="fa fa-check"></i><b>10.3.1</b> Objetos aesteticos</a></li>
<li class="chapter" data-level="10.3.2" data-path="ggplot.html"><a href="ggplot.html#objetos-geométricos-o-capas"><i class="fa fa-check"></i><b>10.3.2</b> Objetos geométricos o capas</a></li>
<li class="chapter" data-level="10.3.3" data-path="ggplot.html"><a href="ggplot.html#facetas"><i class="fa fa-check"></i><b>10.3.3</b> Facetas</a></li>
<li class="chapter" data-level="10.3.4" data-path="ggplot.html"><a href="ggplot.html#más-sobre-estéticas"><i class="fa fa-check"></i><b>10.3.4</b> Más sobre estéticas</a></li>
<li class="chapter" data-level="10.3.5" data-path="ggplot.html"><a href="ggplot.html#un-vistazo-rápido-a-los-datos"><i class="fa fa-check"></i><b>10.3.5</b> Un vistazo rápido a los datos</a></li>
<li class="chapter" data-level="10.3.6" data-path="ggplot.html"><a href="ggplot.html#análisis-univariado"><i class="fa fa-check"></i><b>10.3.6</b> Análisis univariado</a></li>
<li class="chapter" data-level="10.3.7" data-path="ggplot.html"><a href="ggplot.html#análisis-multivariado"><i class="fa fa-check"></i><b>10.3.7</b> Análisis multivariado</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="./"><img src="img/amat-logo.png" width="280"></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introducción a Ciencia de Datos con R (Tidyverse)</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="tidyverse" class="section level1" number="9">
<h1><span class="header-section-number">Capítulo 9</span> Tidyverse</h1>
<div class="watermark">
<p><img src="img/header.png" width="400"/></p>
</div>
<div id="consultas-de-datos-dplyr" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> Consultas de datos (dplyr)</h2>
<p>Ahora que ya sabemos como cargar datos, aprenderemos como manipularlos con <em>dplyr.</em> El paquete <em>dplyr</em> proporciona un conjunto de funciones muy útiles para manipular data frames y así reducir el número de repeticiones, la probabilidad de cometer errores y el número de caracteres que hay que escribir. Como valor extra, podemos encontrar que la gramática de <em>dplyr</em> es más fácil de entender.</p>
<p>Revisaremos algunas de sus funciones <strong>más usadas</strong> (<em>verbos</em>), así como el uso de <strong>pipes</strong> (%&gt;%) para combinarlas.</p>
<ul>
<li><p>select()</p></li>
<li><p>filter()</p></li>
<li><p>arrange()</p></li>
<li><p>mutate()</p></li>
<li><p>summarise()</p></li>
<li><p>join()</p></li>
<li><p>group_by()</p></li>
</ul>
<p>Primero tenemos que instalar y cargar la paquetería (parte de tidyverse):</p>
<div class="sourceCode" id="cb212"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb212-1"><a href="tidyverse.html#cb212-1" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages(&quot;dplyr&quot;)</span></span>
<span id="cb212-2"><a href="tidyverse.html#cb212-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<p>Usaremos el dataset <em>iris</em> que se encuentra en la paquetería <em>datasets</em> (el alumno puede hacer el ejercicio con la base AmesHousing)</p>
<div class="sourceCode" id="cb213"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb213-1"><a href="tidyverse.html#cb213-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(iris,<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1           5.1         3.5          1.4         0.2  setosa
## 2           4.9         3.0          1.4         0.2  setosa
## 3           4.7         3.2          1.3         0.2  setosa
## 4           4.6         3.1          1.5         0.2  setosa
## 5           5.0         3.6          1.4         0.2  setosa
## 6           5.4         3.9          1.7         0.4  setosa
## 7           4.6         3.4          1.4         0.3  setosa
## 8           5.0         3.4          1.5         0.2  setosa
## 9           4.4         2.9          1.4         0.2  setosa
## 10          4.9         3.1          1.5         0.1  setosa</code></pre>
<div id="select" class="section level3" number="9.1.1">
<h3><span class="header-section-number">9.1.1</span> select()</h3>
<p>Observamos que nuestros datos tienen 150 observaciones y 5 variables, con <em>select()</em> podemos seleccionar las variables que le indiquemos.</p>
<div class="sourceCode" id="cb215"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb215-1"><a href="tidyverse.html#cb215-1" aria-hidden="true" tabindex="-1"></a>select_ejemplo<span class="ot">&lt;-</span>iris <span class="sc">%&gt;%</span> <span class="fu">select</span>(Sepal.Length,Petal.Length,Species)</span>
<span id="cb215-2"><a href="tidyverse.html#cb215-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(select_ejemplo,<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    Sepal.Length Petal.Length Species
## 1           5.1          1.4  setosa
## 2           4.9          1.4  setosa
## 3           4.7          1.3  setosa
## 4           4.6          1.5  setosa
## 5           5.0          1.4  setosa
## 6           5.4          1.7  setosa
## 7           4.6          1.4  setosa
## 8           5.0          1.5  setosa
## 9           4.4          1.4  setosa
## 10          4.9          1.5  setosa</code></pre>
<p>El operador pipe (%&gt;%) se usa para conectar múltiples acciones, en este caso solo le indicamos que en los datos de iris se seleccionan 3 varibles y se guarda este nuevo data frame en la variable <em>select_ejemplo</em>.</p>
<p>Con <em>select()</em> y <em>contains</em> podemos seleccionar varibles con alguna cadena de texto.</p>
<div class="sourceCode" id="cb217"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb217-1"><a href="tidyverse.html#cb217-1" aria-hidden="true" tabindex="-1"></a>select_ejemplo<span class="ot">&lt;-</span>iris <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">contains</span>(<span class="st">&quot;Sepal&quot;</span>))</span>
<span id="cb217-2"><a href="tidyverse.html#cb217-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(select_ejemplo,<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width
## 1          5.1         3.5
## 2          4.9         3.0
## 3          4.7         3.2
## 4          4.6         3.1
## 5          5.0         3.6</code></pre>
<p>De igual manera, con <em>select()</em>, <em>ends_with</em> y <em>start_with()</em> podemos seleccionar que inicien o terminen con alguna cadena de texto.</p>
<div class="sourceCode" id="cb219"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb219-1"><a href="tidyverse.html#cb219-1" aria-hidden="true" tabindex="-1"></a>select_ejemplo<span class="ot">&lt;-</span>iris <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="fu">starts_with</span>(<span class="st">&quot;Sepal&quot;</span>),<span class="fu">ends_with</span>(<span class="st">&quot;Length&quot;</span>))</span>
<span id="cb219-2"><a href="tidyverse.html#cb219-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(select_ejemplo,<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length
## 1          5.1         3.5          1.4
## 2          4.9         3.0          1.4
## 3          4.7         3.2          1.3
## 4          4.6         3.1          1.5
## 5          5.0         3.6          1.4</code></pre>
<p>Funciones útiles para <em>select()</em>:</p>
<ul>
<li><p><em>contains()</em>: Selecciona variables cuyo nombre contiene la cadena de texto.</p></li>
<li><p><em>ends_with()</em>: Selecciona variables cuyo nombre termina con la cadena de caracteres.</p></li>
<li><p><em>everything()</em>: Selecciona todas las columnas.</p></li>
<li><p><em>matches()</em>: Selecciona las variables cuyos nombres coinciden con una expresión regular.</p></li>
<li><p><em>num_range()</em>: Selecciona las variables por posición.</p></li>
<li><p><em>start_with()</em>: Selecciona variables cuyos nombres empiezan con la cadena de caracteres.</p></li>
<li><p><em>any_of</em>: Selecciona cualquiera de estas variables, en caso de existir</p></li>
</ul>
</div>
<div id="filter" class="section level3" number="9.1.2">
<h3><span class="header-section-number">9.1.2</span> filter()</h3>
<p>La función filter nos permite filtrar filas según una condición, primero notemos que la variable <em>Species</em> tiene tres categorías.</p>
<div class="sourceCode" id="cb221"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb221-1"><a href="tidyverse.html#cb221-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(iris<span class="sc">$</span>Species)</span></code></pre></div>
<pre><code>## 
##     setosa versicolor  virginica 
##         50         50         50</code></pre>
<p>Ahora usaremos la función <em>filter</em> para quedarnos solo con las observaciones de la especie virginica.</p>
<div class="sourceCode" id="cb223"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb223-1"><a href="tidyverse.html#cb223-1" aria-hidden="true" tabindex="-1"></a>ejemplo_filter<span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Species<span class="sc">==</span><span class="st">&quot;virginica&quot;</span>)</span>
<span id="cb223-2"><a href="tidyverse.html#cb223-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ejemplo_filter,<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 1          6.3         3.3          6.0         2.5 virginica
## 2          5.8         2.7          5.1         1.9 virginica
## 3          7.1         3.0          5.9         2.1 virginica
## 4          6.3         2.9          5.6         1.8 virginica
## 5          6.5         3.0          5.8         2.2 virginica</code></pre>
<p>También se puede usar para filtrar variables numéricas:</p>
<div class="sourceCode" id="cb225"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb225-1"><a href="tidyverse.html#cb225-1" aria-hidden="true" tabindex="-1"></a>ejemplo_filter<span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sepal.Length<span class="sc">&gt;</span><span class="dv">5</span> <span class="sc">&amp;</span> Sepal.Width<span class="sc">&gt;=</span><span class="fl">3.5</span>)</span>
<span id="cb225-2"><a href="tidyverse.html#cb225-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ejemplo_filter,<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          5.4         3.9          1.7         0.4  setosa
## 3          5.4         3.7          1.5         0.2  setosa
## 4          5.8         4.0          1.2         0.2  setosa
## 5          5.7         4.4          1.5         0.4  setosa</code></pre>
<p>Notemos que en el ejemplo anterior usamos <em>&amp;</em>, que nos ayuda a filtrar por dos condiciones.</p>
<p>También podemos usar <em>|</em> para filtrar por alguna de las dos condiciones.</p>
<div class="sourceCode" id="cb227"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb227-1"><a href="tidyverse.html#cb227-1" aria-hidden="true" tabindex="-1"></a>ejemplo_filter<span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Sepal.Length<span class="sc">&gt;</span><span class="dv">5</span> <span class="sc">|</span> Sepal.Width<span class="sc">&gt;=</span><span class="fl">3.5</span>)</span>
<span id="cb227-2"><a href="tidyverse.html#cb227-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ejemplo_filter,<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1          5.1         3.5          1.4         0.2  setosa
## 2          5.0         3.6          1.4         0.2  setosa
## 3          5.4         3.9          1.7         0.4  setosa
## 4          5.4         3.7          1.5         0.2  setosa
## 5          5.8         4.0          1.2         0.2  setosa</code></pre>
<p>Las condiciones pueden ser expresiones lógicas construidas mediante los operadores relacionales y lógicos:</p>
<ul>
<li><p><strong>&lt;</strong> : Menor que</p></li>
<li><p><strong>&gt;</strong> : Mayor que</p></li>
<li><p><strong>=</strong> : Igual que</p></li>
<li><p><strong>&lt;=</strong> : Menor o igual que</p></li>
<li><p><strong>&gt;=</strong> : Mayor o igual que</p></li>
<li><p><strong>!=</strong> : Diferente que</p></li>
<li><p><strong>%in%</strong> : Pertenece al conjunto</p></li>
<li><p><strong>is.na</strong> : Es NA</p></li>
<li><p><strong>!is.na</strong> : No es NA</p></li>
</ul>
</div>
<div id="arrange" class="section level3" number="9.1.3">
<h3><span class="header-section-number">9.1.3</span> arrange()</h3>
<p>La función arrange() se utiliza para ordenar las filas de un data frame de acuerdo a una o varias variables.</p>
<p>Por defecto arrange() ordena las filas por orden ascendente:</p>
<div class="sourceCode" id="cb229"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb229-1"><a href="tidyverse.html#cb229-1" aria-hidden="true" tabindex="-1"></a>ejemplo_arrange<span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(Sepal.Length)</span>
<span id="cb229-2"><a href="tidyverse.html#cb229-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ejemplo_arrange,<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species
## 1           4.3         3.0          1.1         0.1  setosa
## 2           4.4         2.9          1.4         0.2  setosa
## 3           4.4         3.0          1.3         0.2  setosa
## 4           4.4         3.2          1.3         0.2  setosa
## 5           4.5         2.3          1.3         0.3  setosa
## 6           4.6         3.1          1.5         0.2  setosa
## 7           4.6         3.4          1.4         0.3  setosa
## 8           4.6         3.6          1.0         0.2  setosa
## 9           4.6         3.2          1.4         0.2  setosa
## 10          4.7         3.2          1.3         0.2  setosa</code></pre>
<p><br>
<br>
Si las queremos ordenar de forma ascendente lo haremos del siguiente modo:</p>
<div class="sourceCode" id="cb231"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb231-1"><a href="tidyverse.html#cb231-1" aria-hidden="true" tabindex="-1"></a>ejemplo_arrange<span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(Sepal.Length))</span>
<span id="cb231-2"><a href="tidyverse.html#cb231-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ejemplo_arrange,<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##    Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
## 1           7.9         3.8          6.4         2.0 virginica
## 2           7.7         3.8          6.7         2.2 virginica
## 3           7.7         2.6          6.9         2.3 virginica
## 4           7.7         2.8          6.7         2.0 virginica
## 5           7.7         3.0          6.1         2.3 virginica
## 6           7.6         3.0          6.6         2.1 virginica
## 7           7.4         2.8          6.1         1.9 virginica
## 8           7.3         2.9          6.3         1.8 virginica
## 9           7.2         3.6          6.1         2.5 virginica
## 10          7.2         3.2          6.0         1.8 virginica</code></pre>
</div>
<div id="mutate" class="section level3" number="9.1.4">
<h3><span class="header-section-number">9.1.4</span> mutate()</h3>
<p>Con la función mutate() podemos computar tranformaciones de variables en un data frame. A menudo, tendremos la necesidad de crear nuevas variables que se calculan a partir de variables existentes,mutate() nos proporciona una interface clara para realizar este tipo de operaciones.</p>
<p>Por ejemplo haremos la suma de las variables <em>Sepal.Lenght</em> y <em>Sepal.Width</em>:</p>
<div class="sourceCode" id="cb233"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb233-1"><a href="tidyverse.html#cb233-1" aria-hidden="true" tabindex="-1"></a>ejemplo_mutate<span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> <span class="fu">select</span>(Sepal.Length,Sepal.Width) <span class="sc">%&gt;%</span></span>
<span id="cb233-2"><a href="tidyverse.html#cb233-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Suma=</span>Sepal.Length<span class="sc">+</span>Sepal.Width)</span>
<span id="cb233-3"><a href="tidyverse.html#cb233-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(ejemplo_mutate,<span class="dv">5</span>)</span></code></pre></div>
<pre><code>##   Sepal.Length Sepal.Width Suma
## 1          5.1         3.5  8.6
## 2          4.9         3.0  7.9
## 3          4.7         3.2  7.9
## 4          4.6         3.1  7.7
## 5          5.0         3.6  8.6</code></pre>
<p>Notemos que en el ejemplo anterior usamos dos <em>pipes</em> (%&gt;%), como habiamos mencionado se pueden usar los necesarios para combinar funciones.</p>
</div>
<div id="summarise" class="section level3" number="9.1.5">
<h3><span class="header-section-number">9.1.5</span> summarise()</h3>
<p>La función summarise() funciona de forma análoga a la función mutate, excepto que en lugar de añadir nuevas columnas crea un nuevo data frame.</p>
<p>Podemos usar el ejemplo anterior y calcular la media de la varible creada <em>Suma</em>:</p>
<div class="sourceCode" id="cb235"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb235-1"><a href="tidyverse.html#cb235-1" aria-hidden="true" tabindex="-1"></a>ejemplo_summarise<span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span> <span class="fu">select</span>(Sepal.Length,Sepal.Width) <span class="sc">%&gt;%</span></span>
<span id="cb235-2"><a href="tidyverse.html#cb235-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Suma=</span>Sepal.Length<span class="sc">+</span>Sepal.Width) <span class="sc">%&gt;%</span></span>
<span id="cb235-3"><a href="tidyverse.html#cb235-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Media_Suma=</span><span class="fu">mean</span>(Suma))</span>
<span id="cb235-4"><a href="tidyverse.html#cb235-4" aria-hidden="true" tabindex="-1"></a>ejemplo_summarise</span></code></pre></div>
<pre><code>##   Media_Suma
## 1   8.900667</code></pre>
<p>Solo fue necesario agregar un <em>pipe</em>, especificar el nombre de la varible creada y la operación a realizar.</p>
<p>A continuación se muestran funciones que trabajando conjuntamente con la función summarise() facilitarán nuestro trabajo diario. Las primeras pertenecen al paquete base y las otras son del paquete dplyr. Todas ellas toman como argumento un vector y devuelven un único resultado:</p>
<ul>
<li><p><em>min(), max()</em> : Valores max y min.</p></li>
<li><p><em>mean()</em> : Media.</p></li>
<li><p><em>median()</em> : Mediana.</p></li>
<li><p><em>sum()</em> : Suma de los valores.</p></li>
<li><p><em>var(), sd()</em> : Varianza y desviación estandar.</p></li>
<li><p><em>first()</em> : Primer valor en un vector.</p></li>
<li><p><em>last()</em> : El último valor en un vector</p></li>
<li><p><em>n()</em> : El número de valores en un vector.</p></li>
<li><p><em>n_distinc()</em> : El número de valores distintos en un vector.</p></li>
<li><p><em>nth()</em> : Extrar el valor que ocupa la posición n en un vector.</p></li>
</ul>
<p>Mas adelante veremos como combinar esta función con la función <em>group_by</em>.</p>
</div>
<div id="group_by" class="section level3" number="9.1.6">
<h3><span class="header-section-number">9.1.6</span> group_by()</h3>
<p>La función group_by() agrupa un conjunto de filas seleccionado en un conjunto de filas de resumen de acuerdo con los valores de una o más columnas o expresiones.</p>
<p>Usaremos el ejemplo anterior, primero creamos nuestra nueva variable <em>Suma</em>, despues agrupamos por especie y al final sacamos la media de la variable <em>Suma</em> pero esta vez, por la función <em>group_by</em>, nos regresara una media por cada grupo creado, es decir, nos regresara el promedio de la suma por especie.</p>
<div class="sourceCode" id="cb237"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb237-1"><a href="tidyverse.html#cb237-1" aria-hidden="true" tabindex="-1"></a>ejemplo_groupby<span class="ot">&lt;-</span> iris <span class="sc">%&gt;%</span></span>
<span id="cb237-2"><a href="tidyverse.html#cb237-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Suma=</span>Sepal.Length<span class="sc">+</span>Sepal.Width) <span class="sc">%&gt;%</span></span>
<span id="cb237-3"><a href="tidyverse.html#cb237-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Species) <span class="sc">%&gt;%</span></span>
<span id="cb237-4"><a href="tidyverse.html#cb237-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Media_Suma=</span><span class="fu">mean</span>(Suma))</span>
<span id="cb237-5"><a href="tidyverse.html#cb237-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb237-6"><a href="tidyverse.html#cb237-6" aria-hidden="true" tabindex="-1"></a>ejemplo_groupby</span></code></pre></div>
<pre><code>## # A tibble: 3 × 2
##   Species    Media_Suma
##   &lt;fct&gt;           &lt;dbl&gt;
## 1 setosa           8.43
## 2 versicolor       8.71
## 3 virginica        9.56</code></pre>
</div>
<div id="rowwise" class="section level3" number="9.1.7">
<h3><span class="header-section-number">9.1.7</span> rowwise()</h3>
<p>Esta función permite calcular nuevas variables <em>un renglón a la vez</em>.</p>
<div class="sourceCode" id="cb239"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb239-1"><a href="tidyverse.html#cb239-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">%&gt;%</span> </span>
<span id="cb239-2"><a href="tidyverse.html#cb239-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">suma =</span> <span class="fu">sum</span>(Sepal.Length, Sepal.Width, Petal.Length, Petal.Width)) <span class="sc">%&gt;%</span> </span>
<span id="cb239-3"><a href="tidyverse.html#cb239-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>##     Sepal.Length Sepal.Width Petal.Length Petal.Width    Species   suma
## 1            5.1         3.5          1.4         0.2     setosa 2078.7
## 2            4.9         3.0          1.4         0.2     setosa 2078.7
## 3            4.7         3.2          1.3         0.2     setosa 2078.7
## 4            4.6         3.1          1.5         0.2     setosa 2078.7
## 5            5.0         3.6          1.4         0.2     setosa 2078.7
## 6            5.4         3.9          1.7         0.4     setosa 2078.7
## 7            4.6         3.4          1.4         0.3     setosa 2078.7
## 8            5.0         3.4          1.5         0.2     setosa 2078.7
## 9            4.4         2.9          1.4         0.2     setosa 2078.7
## 10           4.9         3.1          1.5         0.1     setosa 2078.7
## 11           5.4         3.7          1.5         0.2     setosa 2078.7
## 12           4.8         3.4          1.6         0.2     setosa 2078.7
## 13           4.8         3.0          1.4         0.1     setosa 2078.7
## 14           4.3         3.0          1.1         0.1     setosa 2078.7
## 15           5.8         4.0          1.2         0.2     setosa 2078.7
## 16           5.7         4.4          1.5         0.4     setosa 2078.7
## 17           5.4         3.9          1.3         0.4     setosa 2078.7
## 18           5.1         3.5          1.4         0.3     setosa 2078.7
## 19           5.7         3.8          1.7         0.3     setosa 2078.7
## 20           5.1         3.8          1.5         0.3     setosa 2078.7
## 21           5.4         3.4          1.7         0.2     setosa 2078.7
## 22           5.1         3.7          1.5         0.4     setosa 2078.7
## 23           4.6         3.6          1.0         0.2     setosa 2078.7
## 24           5.1         3.3          1.7         0.5     setosa 2078.7
## 25           4.8         3.4          1.9         0.2     setosa 2078.7
## 26           5.0         3.0          1.6         0.2     setosa 2078.7
## 27           5.0         3.4          1.6         0.4     setosa 2078.7
## 28           5.2         3.5          1.5         0.2     setosa 2078.7
## 29           5.2         3.4          1.4         0.2     setosa 2078.7
## 30           4.7         3.2          1.6         0.2     setosa 2078.7
## 31           4.8         3.1          1.6         0.2     setosa 2078.7
## 32           5.4         3.4          1.5         0.4     setosa 2078.7
## 33           5.2         4.1          1.5         0.1     setosa 2078.7
## 34           5.5         4.2          1.4         0.2     setosa 2078.7
## 35           4.9         3.1          1.5         0.2     setosa 2078.7
## 36           5.0         3.2          1.2         0.2     setosa 2078.7
## 37           5.5         3.5          1.3         0.2     setosa 2078.7
## 38           4.9         3.6          1.4         0.1     setosa 2078.7
## 39           4.4         3.0          1.3         0.2     setosa 2078.7
## 40           5.1         3.4          1.5         0.2     setosa 2078.7
## 41           5.0         3.5          1.3         0.3     setosa 2078.7
## 42           4.5         2.3          1.3         0.3     setosa 2078.7
## 43           4.4         3.2          1.3         0.2     setosa 2078.7
## 44           5.0         3.5          1.6         0.6     setosa 2078.7
## 45           5.1         3.8          1.9         0.4     setosa 2078.7
## 46           4.8         3.0          1.4         0.3     setosa 2078.7
## 47           5.1         3.8          1.6         0.2     setosa 2078.7
## 48           4.6         3.2          1.4         0.2     setosa 2078.7
## 49           5.3         3.7          1.5         0.2     setosa 2078.7
## 50           5.0         3.3          1.4         0.2     setosa 2078.7
## 51           7.0         3.2          4.7         1.4 versicolor 2078.7
## 52           6.4         3.2          4.5         1.5 versicolor 2078.7
## 53           6.9         3.1          4.9         1.5 versicolor 2078.7
## 54           5.5         2.3          4.0         1.3 versicolor 2078.7
## 55           6.5         2.8          4.6         1.5 versicolor 2078.7
## 56           5.7         2.8          4.5         1.3 versicolor 2078.7
## 57           6.3         3.3          4.7         1.6 versicolor 2078.7
## 58           4.9         2.4          3.3         1.0 versicolor 2078.7
## 59           6.6         2.9          4.6         1.3 versicolor 2078.7
## 60           5.2         2.7          3.9         1.4 versicolor 2078.7
## 61           5.0         2.0          3.5         1.0 versicolor 2078.7
## 62           5.9         3.0          4.2         1.5 versicolor 2078.7
## 63           6.0         2.2          4.0         1.0 versicolor 2078.7
## 64           6.1         2.9          4.7         1.4 versicolor 2078.7
## 65           5.6         2.9          3.6         1.3 versicolor 2078.7
## 66           6.7         3.1          4.4         1.4 versicolor 2078.7
## 67           5.6         3.0          4.5         1.5 versicolor 2078.7
## 68           5.8         2.7          4.1         1.0 versicolor 2078.7
## 69           6.2         2.2          4.5         1.5 versicolor 2078.7
## 70           5.6         2.5          3.9         1.1 versicolor 2078.7
## 71           5.9         3.2          4.8         1.8 versicolor 2078.7
## 72           6.1         2.8          4.0         1.3 versicolor 2078.7
## 73           6.3         2.5          4.9         1.5 versicolor 2078.7
## 74           6.1         2.8          4.7         1.2 versicolor 2078.7
## 75           6.4         2.9          4.3         1.3 versicolor 2078.7
## 76           6.6         3.0          4.4         1.4 versicolor 2078.7
## 77           6.8         2.8          4.8         1.4 versicolor 2078.7
## 78           6.7         3.0          5.0         1.7 versicolor 2078.7
## 79           6.0         2.9          4.5         1.5 versicolor 2078.7
## 80           5.7         2.6          3.5         1.0 versicolor 2078.7
## 81           5.5         2.4          3.8         1.1 versicolor 2078.7
## 82           5.5         2.4          3.7         1.0 versicolor 2078.7
## 83           5.8         2.7          3.9         1.2 versicolor 2078.7
## 84           6.0         2.7          5.1         1.6 versicolor 2078.7
## 85           5.4         3.0          4.5         1.5 versicolor 2078.7
## 86           6.0         3.4          4.5         1.6 versicolor 2078.7
## 87           6.7         3.1          4.7         1.5 versicolor 2078.7
## 88           6.3         2.3          4.4         1.3 versicolor 2078.7
## 89           5.6         3.0          4.1         1.3 versicolor 2078.7
## 90           5.5         2.5          4.0         1.3 versicolor 2078.7
## 91           5.5         2.6          4.4         1.2 versicolor 2078.7
## 92           6.1         3.0          4.6         1.4 versicolor 2078.7
## 93           5.8         2.6          4.0         1.2 versicolor 2078.7
## 94           5.0         2.3          3.3         1.0 versicolor 2078.7
## 95           5.6         2.7          4.2         1.3 versicolor 2078.7
## 96           5.7         3.0          4.2         1.2 versicolor 2078.7
## 97           5.7         2.9          4.2         1.3 versicolor 2078.7
## 98           6.2         2.9          4.3         1.3 versicolor 2078.7
## 99           5.1         2.5          3.0         1.1 versicolor 2078.7
## 100          5.7         2.8          4.1         1.3 versicolor 2078.7
## 101          6.3         3.3          6.0         2.5  virginica 2078.7
## 102          5.8         2.7          5.1         1.9  virginica 2078.7
## 103          7.1         3.0          5.9         2.1  virginica 2078.7
## 104          6.3         2.9          5.6         1.8  virginica 2078.7
## 105          6.5         3.0          5.8         2.2  virginica 2078.7
## 106          7.6         3.0          6.6         2.1  virginica 2078.7
## 107          4.9         2.5          4.5         1.7  virginica 2078.7
## 108          7.3         2.9          6.3         1.8  virginica 2078.7
## 109          6.7         2.5          5.8         1.8  virginica 2078.7
## 110          7.2         3.6          6.1         2.5  virginica 2078.7
## 111          6.5         3.2          5.1         2.0  virginica 2078.7
## 112          6.4         2.7          5.3         1.9  virginica 2078.7
## 113          6.8         3.0          5.5         2.1  virginica 2078.7
## 114          5.7         2.5          5.0         2.0  virginica 2078.7
## 115          5.8         2.8          5.1         2.4  virginica 2078.7
## 116          6.4         3.2          5.3         2.3  virginica 2078.7
## 117          6.5         3.0          5.5         1.8  virginica 2078.7
## 118          7.7         3.8          6.7         2.2  virginica 2078.7
## 119          7.7         2.6          6.9         2.3  virginica 2078.7
## 120          6.0         2.2          5.0         1.5  virginica 2078.7
## 121          6.9         3.2          5.7         2.3  virginica 2078.7
## 122          5.6         2.8          4.9         2.0  virginica 2078.7
## 123          7.7         2.8          6.7         2.0  virginica 2078.7
## 124          6.3         2.7          4.9         1.8  virginica 2078.7
## 125          6.7         3.3          5.7         2.1  virginica 2078.7
## 126          7.2         3.2          6.0         1.8  virginica 2078.7
## 127          6.2         2.8          4.8         1.8  virginica 2078.7
## 128          6.1         3.0          4.9         1.8  virginica 2078.7
## 129          6.4         2.8          5.6         2.1  virginica 2078.7
## 130          7.2         3.0          5.8         1.6  virginica 2078.7
## 131          7.4         2.8          6.1         1.9  virginica 2078.7
## 132          7.9         3.8          6.4         2.0  virginica 2078.7
## 133          6.4         2.8          5.6         2.2  virginica 2078.7
## 134          6.3         2.8          5.1         1.5  virginica 2078.7
## 135          6.1         2.6          5.6         1.4  virginica 2078.7
## 136          7.7         3.0          6.1         2.3  virginica 2078.7
## 137          6.3         3.4          5.6         2.4  virginica 2078.7
## 138          6.4         3.1          5.5         1.8  virginica 2078.7
## 139          6.0         3.0          4.8         1.8  virginica 2078.7
## 140          6.9         3.1          5.4         2.1  virginica 2078.7
## 141          6.7         3.1          5.6         2.4  virginica 2078.7
## 142          6.9         3.1          5.1         2.3  virginica 2078.7
## 143          5.8         2.7          5.1         1.9  virginica 2078.7
## 144          6.8         3.2          5.9         2.3  virginica 2078.7
## 145          6.7         3.3          5.7         2.5  virginica 2078.7
## 146          6.7         3.0          5.2         2.3  virginica 2078.7
## 147          6.3         2.5          5.0         1.9  virginica 2078.7
## 148          6.5         3.0          5.2         2.0  virginica 2078.7
## 149          6.2         3.4          5.4         2.3  virginica 2078.7
## 150          5.9         3.0          5.1         1.8  virginica 2078.7</code></pre>
<p>¿Qué pasó en el ejemplo pasado?</p>
<p>Ahora veamos qué pasa al intriducir rowwise al pipeline</p>
<div class="sourceCode" id="cb241"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb241-1"><a href="tidyverse.html#cb241-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">%&gt;%</span> </span>
<span id="cb241-2"><a href="tidyverse.html#cb241-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb241-3"><a href="tidyverse.html#cb241-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">suma =</span> Sepal.Length <span class="sc">+</span> Sepal.Width <span class="sc">+</span> Petal.Length <span class="sc">+</span> Petal.Width) <span class="sc">%&gt;%</span> </span>
<span id="cb241-4"><a href="tidyverse.html#cb241-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## # A tibble: 150 × 6
##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species  suma
##           &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt; &lt;fct&gt;   &lt;dbl&gt;
##  1          5.1         3.5          1.4         0.2 setosa   10.2
##  2          4.9         3            1.4         0.2 setosa    9.5
##  3          4.7         3.2          1.3         0.2 setosa    9.4
##  4          4.6         3.1          1.5         0.2 setosa    9.4
##  5          5           3.6          1.4         0.2 setosa   10.2
##  6          5.4         3.9          1.7         0.4 setosa   11.4
##  7          4.6         3.4          1.4         0.3 setosa    9.7
##  8          5           3.4          1.5         0.2 setosa   10.1
##  9          4.4         2.9          1.4         0.2 setosa    8.9
## 10          4.9         3.1          1.5         0.1 setosa    9.6
## # … with 140 more rows</code></pre>
<div class="sourceCode" id="cb243"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb243-1"><a href="tidyverse.html#cb243-1" aria-hidden="true" tabindex="-1"></a>iris <span class="sc">%&gt;%</span> </span>
<span id="cb243-2"><a href="tidyverse.html#cb243-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rowwise</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb243-3"><a href="tidyverse.html#cb243-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">suma =</span> <span class="fu">sum</span>(<span class="fu">across</span>(Sepal.Length<span class="sc">:</span>Petal.Width))) <span class="sc">%&gt;%</span> </span>
<span id="cb243-4"><a href="tidyverse.html#cb243-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code></pre></div>
<pre><code>## # A tibble: 150 × 6
##    Sepal.Length Sepal.Width Petal.Length Petal.Width Species  suma
##           &lt;dbl&gt;       &lt;dbl&gt;        &lt;dbl&gt;       &lt;dbl&gt; &lt;fct&gt;   &lt;dbl&gt;
##  1          5.1         3.5          1.4         0.2 setosa   10.2
##  2          4.9         3            1.4         0.2 setosa    9.5
##  3          4.7         3.2          1.3         0.2 setosa    9.4
##  4          4.6         3.1          1.5         0.2 setosa    9.4
##  5          5           3.6          1.4         0.2 setosa   10.2
##  6          5.4         3.9          1.7         0.4 setosa   11.4
##  7          4.6         3.4          1.4         0.3 setosa    9.7
##  8          5           3.4          1.5         0.2 setosa   10.1
##  9          4.4         2.9          1.4         0.2 setosa    8.9
## 10          4.9         3.1          1.5         0.1 setosa    9.6
## # … with 140 more rows</code></pre>
</div>
</div>
<div id="cruces-de-tablas" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> Cruces de tablas</h2>
<p>Una operación fundamental por agregar a nuestro flujo de trabajo es el cruce de tablas, las cuales pueden proceder de la misma o de distinta fuente. Comúnmente <strong>este proceso se realiza para enriquecer y unificar la información</strong> proveniente de distintas tablas de datos.</p>
<p>Para lograr esta tarea es indispensable que exista una variable <strong>llave</strong> en ambos conjuntos de datos que sirva como puente o identificador de cada caso o renglón. Si se cuenta con la columna llave entonces será posible cruzar las tablas y lograr su enriquecimiento.</p>
<p>En el siguiente ejemplo se muestra el uso de la variable llave a través de la columna “ID.” Se puede apreciar que en la tabla final se cuenta con información de la variable “Weight” para los elementos que existen en las tablas “A” y “B.”</p>
<p><img src="img/03-tidyverse/left_join3.png" width="700pt" style="display: block; margin: auto;" /></p>
<p>La función que hace posible el complemento de la información es llamada <em>left_join()</em>. El primer argumento de la función corresponde al conjunto de datos que se desea complementar, mientras que en el segundo argumento se ingresa el conjunto de datos con la información que enriquecerá al primer conjunto. Es necesario especificar en el argumento <em>“by”</em> el nombre de la columna llave.</p>
<div class="sourceCode" id="cb245"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb245-1"><a href="tidyverse.html#cb245-1" aria-hidden="true" tabindex="-1"></a>conjuntoX <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">&quot;Llave&quot;</span> <span class="ot">=</span> LETTERS[<span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>], <span class="st">&quot;C1&quot;</span> <span class="ot">=</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">8</span>)</span>
<span id="cb245-2"><a href="tidyverse.html#cb245-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb245-3"><a href="tidyverse.html#cb245-3" aria-hidden="true" tabindex="-1"></a>conjuntoY <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="st">&quot;Llave&quot;</span> <span class="ot">=</span> <span class="fu">sample</span>(LETTERS[<span class="dv">11</span><span class="sc">:</span><span class="dv">3</span>], <span class="at">size =</span> <span class="dv">9</span>, <span class="at">replace =</span> T), </span>
<span id="cb245-4"><a href="tidyverse.html#cb245-4" aria-hidden="true" tabindex="-1"></a>                        <span class="st">&quot;Ex1&quot;</span> <span class="ot">=</span> letters[<span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>], </span>
<span id="cb245-5"><a href="tidyverse.html#cb245-5" aria-hidden="true" tabindex="-1"></a>                        <span class="st">&quot;Ex2&quot;</span> <span class="ot">=</span> <span class="dv">1002</span><span class="sc">:</span><span class="dv">1010</span>,<span class="st">&quot;Ex3&quot;</span> <span class="ot">=</span> <span class="fu">paste0</span>(letters[<span class="dv">12</span><span class="sc">:</span><span class="dv">20</span>],<span class="dv">2</span><span class="sc">:</span><span class="dv">10</span>))</span>
<span id="cb245-6"><a href="tidyverse.html#cb245-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb245-7"><a href="tidyverse.html#cb245-7" aria-hidden="true" tabindex="-1"></a>conjuntoX</span></code></pre></div>
<pre><code>##   Llave C1
## 1     A  1
## 2     B  2
## 3     C  3
## 4     D  4
## 5     E  5
## 6     F  6
## 7     G  7
## 8     H  8</code></pre>
<div class="sourceCode" id="cb247"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb247-1"><a href="tidyverse.html#cb247-1" aria-hidden="true" tabindex="-1"></a>conjuntoY</span></code></pre></div>
<pre><code>##   Llave Ex1  Ex2 Ex3
## 1     H   b 1002  l2
## 2     F   c 1003  m3
## 3     F   d 1004  n4
## 4     H   e 1005  o5
## 5     G   f 1006  p6
## 6     D   g 1007  q7
## 7     G   h 1008  r8
## 8     K   i 1009  s9
## 9     F   j 1010 t10</code></pre>
<div class="sourceCode" id="cb249"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb249-1"><a href="tidyverse.html#cb249-1" aria-hidden="true" tabindex="-1"></a><span class="fu">left_join</span>(<span class="at">x =</span> conjuntoX, <span class="at">y =</span> conjuntoY, <span class="at">by =</span> <span class="st">&quot;Llave&quot;</span>)</span></code></pre></div>
<pre><code>##    Llave C1  Ex1  Ex2  Ex3
## 1      A  1 &lt;NA&gt;   NA &lt;NA&gt;
## 2      B  2 &lt;NA&gt;   NA &lt;NA&gt;
## 3      C  3 &lt;NA&gt;   NA &lt;NA&gt;
## 4      D  4    g 1007   q7
## 5      E  5 &lt;NA&gt;   NA &lt;NA&gt;
## 6      F  6    c 1003   m3
## 7      F  6    d 1004   n4
## 8      F  6    j 1010  t10
## 9      G  7    f 1006   p6
## 10     G  7    h 1008   r8
## 11     H  8    b 1002   l2
## 12     H  8    e 1005   o5</code></pre>
<p>Es posible que no todas las observaciones de un conjunto de datos estén en el otro conjunto, cuando esto sucede un aviso aparece indicando que los factores o categorías de la variable llave son diferentes. En caso de no encontrarse uno o más de los valores, el resultado para esos casos será NA (no disponible, por su traducción del inglés “Not Available”), y aparecerá siempre que no se cuente con información en un registro, como se muestra en el ejemplo anterior.</p>
<p>Existen diferentes maneras de conjuntar datos. La primera, como en el ejemplo mostrado anteriormente, se hace por lo izquierda y quiere decir que, <strong>al primer conjunto de datos es al que se le agregará la información del segundo conjunto</strong>. Esto se realizará exclusivamente para aquellos registros del segundo conjunto que existan en el primero, los cuales se identifican mediante la llave definida.</p>
<p>Otra manera de realizar la conjunción de los datos es por la derecha. Funciona de manera análoga a la primera, con la diferencia de que son los datos del primer conjunto los que se agregan al segundo. De igual manera, esto sólo ocurre para los elemento del primer conjunto que se encuentran en el segundo y que son identificables a través de una llave. La función en <em>R</em> que permite realizar la conjunción por la derecha lleva por nombre <em>right_join()</em>.</p>
<div class="sourceCode" id="cb251"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb251-1"><a href="tidyverse.html#cb251-1" aria-hidden="true" tabindex="-1"></a><span class="fu">right_join</span>(<span class="at">x =</span> conjuntoX, <span class="at">y =</span> conjuntoY, <span class="at">by =</span> <span class="st">&quot;Llave&quot;</span>)</span></code></pre></div>
<pre><code>##   Llave C1 Ex1  Ex2 Ex3
## 1     D  4   g 1007  q7
## 2     F  6   c 1003  m3
## 3     F  6   d 1004  n4
## 4     F  6   j 1010 t10
## 5     G  7   f 1006  p6
## 6     G  7   h 1008  r8
## 7     H  8   b 1002  l2
## 8     H  8   e 1005  o5
## 9     K NA   i 1009  s9</code></pre>
<p>Una tercer forma de unir los datos es a través de la función <em>full_join()</em>, la cual es una combinación de las dos anteriores. Agrega todos los elementos llave tanto del primer conjunto como del segundo y posteriormente realiza el cruce de información de ambos conjuntos.</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="tidyverse.html#cb253-1" aria-hidden="true" tabindex="-1"></a><span class="fu">full_join</span>(<span class="at">x =</span> conjuntoX, <span class="at">y =</span> conjuntoY, <span class="at">by =</span> <span class="st">&quot;Llave&quot;</span>)</span></code></pre></div>
<pre><code>##    Llave C1  Ex1  Ex2  Ex3
## 1      A  1 &lt;NA&gt;   NA &lt;NA&gt;
## 2      B  2 &lt;NA&gt;   NA &lt;NA&gt;
## 3      C  3 &lt;NA&gt;   NA &lt;NA&gt;
## 4      D  4    g 1007   q7
## 5      E  5 &lt;NA&gt;   NA &lt;NA&gt;
## 6      F  6    c 1003   m3
## 7      F  6    d 1004   n4
## 8      F  6    j 1010  t10
## 9      G  7    f 1006   p6
## 10     G  7    h 1008   r8
## 11     H  8    b 1002   l2
## 12     H  8    e 1005   o5
## 13     K NA    i 1009   s9</code></pre>
<p>Estos 3 primeros métodos pueden resumirse en la siguiente imagen:</p>
<p><img src="img/03-tidyverse/left_right_full_join.png" width="700pt" style="display: block; margin: auto;" /></p>
<p>Adicionalmente, existen otras funciones que ayudan con gestionar las operaciones entre conjuntos de datos. Tal es el caso de la función <em>inner_join()</em>, la cuál no es otra cosa que el filtro de aquellos elementos que se tengan en común en ambas tablas y la combinación de un <em>join</em>. Internamente, la función primero filtra el ID de aquellos elementos que tienen presencia en ambas tablas y finalmente hace el cruce de los datos.</p>
<p><img src="img/03-tidyverse/inner_join.png" width="700pt" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="tidyverse.html#cb255-1" aria-hidden="true" tabindex="-1"></a><span class="fu">inner_join</span>(<span class="at">x =</span> conjuntoX, <span class="at">y =</span> conjuntoY, <span class="at">by =</span> <span class="st">&quot;Llave&quot;</span>)</span></code></pre></div>
<pre><code>##   Llave C1 Ex1  Ex2 Ex3
## 1     D  4   g 1007  q7
## 2     F  6   c 1003  m3
## 3     F  6   d 1004  n4
## 4     F  6   j 1010 t10
## 5     G  7   f 1006  p6
## 6     G  7   h 1008  r8
## 7     H  8   b 1002  l2
## 8     H  8   e 1005  o5</code></pre>
<p>Existen otras dos operaciones interesantes que agilizan la extracción de subconjuntos de tablas sin cruzar información. Se trata de las funciones <em>semi_join()</em> y <em>anti_join()</em>, las cuales funcionan de la siguiente manera:</p>
<p>La función <em>semi_join()</em> detecta y filtra los elementos del primer conjunto que se encuentran en un segundo conjunto, mientras que la función <em>anti_join()</em> es su complemento, pues regresa los elementos del primer conjunto que no se encuentran en el segundo. En ambos casos, la información contenida en el segundo conjunto no es trasmitida al resultado.</p>
<p><img src="img/03-tidyverse/semi_join.png" width="700pt" style="display: block; margin: auto;" /></p>
<p>A continuación se presenta su ejemplificación:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="tidyverse.html#cb257-1" aria-hidden="true" tabindex="-1"></a><span class="fu">semi_join</span>(<span class="at">x =</span> conjuntoX, <span class="at">y =</span> conjuntoY, <span class="at">by =</span> <span class="st">&quot;Llave&quot;</span>)</span></code></pre></div>
<pre><code>##   Llave C1
## 1     D  4
## 2     F  6
## 3     G  7
## 4     H  8</code></pre>
<p>Ahora revisemos el caso de la función <em>anti_join()</em></p>
<p><img src="img/03-tidyverse/anti_join.png" width="700pt" style="display: block; margin: auto;" /></p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="tidyverse.html#cb259-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anti_join</span>(<span class="at">x =</span> conjuntoX, <span class="at">y =</span> conjuntoY, <span class="at">by =</span> <span class="st">&quot;Llave&quot;</span>)</span></code></pre></div>
<pre><code>##   Llave C1
## 1     A  1
## 2     B  2
## 3     C  3
## 4     E  5</code></pre>
<p><strong>WARNING: llaves duplicadas</strong></p>
<p>La mayoría de los ejemplos anteriores suponen que las llaves son únicas en cada conjunto de datos, sin embargo, esto no es cierto en una gran cantidad de ocasiones. Existen dos casos importantes por analizar:</p>
<ul>
<li>Llaves duplicadas en 1 conjunto de datos</li>
<li>Llaves duplicadas en ambos conjuntos</li>
</ul>
<p>El caso más sencillo es cuando solo uno de los conjuntos contiene llaves duplicadas. En este caso se creará un renglón por cada duplicado.</p>
<p><img src="img/03-tidyverse/duplicado1.png" width="700pt" style="display: block; margin: auto;" /></p>
<p>En el segundo caso, por cada elemento duplicado en el primer conjunto habrá como resultado un elemento por cada duplicado en el segundo conjunto. A continuación se ejemplifica este escenario.</p>
<p><img src="img/03-tidyverse/duplicado2.png" width="700pt" style="display: block; margin: auto;" /></p>
</div>
<div id="órden-y-reestructuración-de-tablas" class="section level2" number="9.3">
<h2><span class="header-section-number">9.3</span> Órden y reestructuración de tablas</h2>
<p>Un conjunto de datos puede ser representado de muchas maneras distintas y contener en todos los casos la misma información. Sin embargo, no todos los modos en que se presenta la información resulta óptimo para su procesamiento y análisis. Los conjuntos de datos ordenados serán más fáciles de trabajar y analizar.</p>
<p>Algunas de las características principales que presentan los conjuntos de datos ordenados son las siguientes:</p>
<ol style="list-style-type: decimal">
<li><p>Cada variable debe tener su propia columna.</p></li>
<li><p>Cada observación debe tener su propio renglón.</p></li>
<li><p>Cada valor debe tener su propia celda.</p></li>
</ol>
<p><img src="img/03-tidyverse/tidy-1.png" width="700pt" style="display: block; margin: auto;" /></p>
<p>La figura anterior muestra la estructura de orden que debe tener un conjunto de datos. A pesar de que pueda parecer intuitivo y sencillo, en la práctica es considerable el número de conjuntos de datos desordenados. La limpieza y ordenamiento debe ser trabajado de forma impecable a fin de que puedan realizarse buenas prácticas. El tiempo de limpieza y ordenamiento varía mucho dependiendo de la dimensión del conjunto de datos.</p>
<p>Algunos de los principales problemas que pueden tener los conjuntos de datos no ordenados son:</p>
<ul>
<li>Una variable puede estar dispersa en múltiples columnas</li>
<li>Una observación puede estar esparcida en múltiples renglones</li>
</ul>
<p>La paquetería <em>tidyr</em> cuenta con funciones para resolver dichos problemas. Entre las principales funciones que tiene la paquetería, se encuentran <em>pivot_longer()</em>, <em>pivot_wider()</em>, <em>separate()</em> y <em>unite()</em>, mismas que se analizarán a continuación.</p>
<div id="pivote-horizontal" class="section level3" number="9.3.1">
<h3><span class="header-section-number">9.3.1</span> Pivote horizontal</h3>
<p>La función <em>pivot_wider()</em> resulta muy útil a la hora de organizar los datos. Su función consiste en <strong>dispersar una variable clave en múltiples columnas</strong>.</p>
<p>Lo primero que se debe hacer para poder hacer uso de dicha función es instalar y cargar la librería.</p>
<p>El siguiente conjunto de datos contiene el número de localidades rurales y urbanas por municipio de la Ciudad de México. Como es posible observar, algunos municipios aparecen más de una vez en el marco de datos, esto se debe a que cada municipio puede tener ambos ámbitos, rural y urbano. Para hacer que el conjunto de datos sea ordenado, es necesario que cada observación aparezca una sola vez por renglón y cada una de las categorías (rural y urbano) de la variable “Ámbito” deberá ocupar el lugar de una columna.</p>
<p>El siguiente código muestra cómo convertir los datos no ordenados en un conjunto ordenado.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="tidyverse.html#cb261-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyr)</span>
<span id="cb261-2"><a href="tidyverse.html#cb261-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb261-3"><a href="tidyverse.html#cb261-3" aria-hidden="true" tabindex="-1"></a>Resumen <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;data/loc_mun_cdmx.rds&quot;</span>)</span>
<span id="cb261-4"><a href="tidyverse.html#cb261-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb261-5"><a href="tidyverse.html#cb261-5" aria-hidden="true" tabindex="-1"></a>Resumen  <span class="sc">%&gt;%</span> <span class="fu">pivot_wider</span>(</span>
<span id="cb261-6"><a href="tidyverse.html#cb261-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">names_from =</span> Ambito, </span>
<span id="cb261-7"><a href="tidyverse.html#cb261-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">values_from =</span>  Total_localidades</span>
<span id="cb261-8"><a href="tidyverse.html#cb261-8" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 16 × 3
##    NOM_MUN                Rural Urbano
##    &lt;chr&gt;                  &lt;int&gt;  &lt;int&gt;
##  1 Álvaro Obregón             3      1
##  2 La Magdalena Contreras     8      1
##  3 Cuajimalpa de Morelos     14      2
##  4 Tláhuac                   31      5
##  5 Xochimilco                78      1
##  6 Tlalpan                   95      4
##  7 Milpa Alta               187     10
##  8 Azcapotzalco              NA      1
##  9 Benito Juárez             NA      1
## 10 Coyoacán                  NA      1
## 11 Cuauhtémoc                NA      1
## 12 Gustavo A. Madero         NA      1
## 13 Iztacalco                 NA      1
## 14 Iztapalapa                NA      1
## 15 Miguel Hidalgo            NA      1
## 16 Venustiano Carranza       NA      1</code></pre>
<p>En la tabla actual existe ahora un y sólo un registro por cada observación (nombre de municipio en este caso). El valor que le corresponde a cada una de las columnas creadas es la frecuencia absoluta de localidades que tienen la característica “Rural” y “Urbano” respectivamente.</p>
<p>Pero… ¿qué pasa cuando no existen todos los valores en ambas columnas? Si no se especifica la manera de llenar los datos faltantes, estos contendrán NAs. Siempre se puede elegir el caracter o número con el cual se imputan los datos faltantes.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="tidyverse.html#cb263-1" aria-hidden="true" tabindex="-1"></a>fish_encounters <span class="sc">%&gt;%</span></span>
<span id="cb263-2"><a href="tidyverse.html#cb263-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> station, <span class="at">values_from =</span> seen)</span></code></pre></div>
<pre><code>## # A tibble: 19 × 12
##    fish  Release I80_1 Lisbon  Rstr Base_TD   BCE   BCW  BCE2  BCW2   MAE   MAW
##    &lt;fct&gt;   &lt;int&gt; &lt;int&gt;  &lt;int&gt; &lt;int&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1 4842        1     1      1     1       1     1     1     1     1     1     1
##  2 4843        1     1      1     1       1     1     1     1     1     1     1
##  3 4844        1     1      1     1       1     1     1     1     1     1     1
##  4 4845        1     1      1     1       1    NA    NA    NA    NA    NA    NA
##  5 4847        1     1      1    NA      NA    NA    NA    NA    NA    NA    NA
##  6 4848        1     1      1     1      NA    NA    NA    NA    NA    NA    NA
##  7 4849        1     1     NA    NA      NA    NA    NA    NA    NA    NA    NA
##  8 4850        1     1     NA     1       1     1     1    NA    NA    NA    NA
##  9 4851        1     1     NA    NA      NA    NA    NA    NA    NA    NA    NA
## 10 4854        1     1     NA    NA      NA    NA    NA    NA    NA    NA    NA
## 11 4855        1     1      1     1       1    NA    NA    NA    NA    NA    NA
## 12 4857        1     1      1     1       1     1     1     1     1    NA    NA
## 13 4858        1     1      1     1       1     1     1     1     1     1     1
## 14 4859        1     1      1     1       1    NA    NA    NA    NA    NA    NA
## 15 4861        1     1      1     1       1     1     1     1     1     1     1
## 16 4862        1     1      1     1       1     1     1     1     1    NA    NA
## 17 4863        1     1     NA    NA      NA    NA    NA    NA    NA    NA    NA
## 18 4864        1     1     NA    NA      NA    NA    NA    NA    NA    NA    NA
## 19 4865        1     1      1    NA      NA    NA    NA    NA    NA    NA    NA</code></pre>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="tidyverse.html#cb265-1" aria-hidden="true" tabindex="-1"></a>fish_encounters <span class="sc">%&gt;%</span></span>
<span id="cb265-2"><a href="tidyverse.html#cb265-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> station, <span class="at">values_from =</span> seen, <span class="at">values_fill =</span> <span class="dv">0</span>)</span></code></pre></div>
<pre><code>## # A tibble: 19 × 12
##    fish  Release I80_1 Lisbon  Rstr Base_TD   BCE   BCW  BCE2  BCW2   MAE   MAW
##    &lt;fct&gt;   &lt;int&gt; &lt;int&gt;  &lt;int&gt; &lt;int&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt;
##  1 4842        1     1      1     1       1     1     1     1     1     1     1
##  2 4843        1     1      1     1       1     1     1     1     1     1     1
##  3 4844        1     1      1     1       1     1     1     1     1     1     1
##  4 4845        1     1      1     1       1     0     0     0     0     0     0
##  5 4847        1     1      1     0       0     0     0     0     0     0     0
##  6 4848        1     1      1     1       0     0     0     0     0     0     0
##  7 4849        1     1      0     0       0     0     0     0     0     0     0
##  8 4850        1     1      0     1       1     1     1     0     0     0     0
##  9 4851        1     1      0     0       0     0     0     0     0     0     0
## 10 4854        1     1      0     0       0     0     0     0     0     0     0
## 11 4855        1     1      1     1       1     0     0     0     0     0     0
## 12 4857        1     1      1     1       1     1     1     1     1     0     0
## 13 4858        1     1      1     1       1     1     1     1     1     1     1
## 14 4859        1     1      1     1       1     0     0     0     0     0     0
## 15 4861        1     1      1     1       1     1     1     1     1     1     1
## 16 4862        1     1      1     1       1     1     1     1     1     0     0
## 17 4863        1     1      0     0       0     0     0     0     0     0     0
## 18 4864        1     1      0     0       0     0     0     0     0     0     0
## 19 4865        1     1      1     0       0     0     0     0     0     0     0</code></pre>
<p>En caso de que existan múltiples columnas que se desean dispersar mediante el pivote de una columna con múltiples categorías, es posible especificar tal reestructuración a través del siguiente código.</p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="tidyverse.html#cb267-1" aria-hidden="true" tabindex="-1"></a>us_rent_income <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(NAME)</span></code></pre></div>
<pre><code>## # A tibble: 104 × 5
##    GEOID NAME       variable estimate   moe
##    &lt;chr&gt; &lt;chr&gt;      &lt;chr&gt;       &lt;dbl&gt; &lt;dbl&gt;
##  1 01    Alabama    income      24476   136
##  2 01    Alabama    rent          747     3
##  3 02    Alaska     income      32940   508
##  4 02    Alaska     rent         1200    13
##  5 04    Arizona    income      27517   148
##  6 04    Arizona    rent          972     4
##  7 05    Arkansas   income      23789   165
##  8 05    Arkansas   rent          709     5
##  9 06    California income      29454   109
## 10 06    California rent         1358     3
## # … with 94 more rows</code></pre>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="tidyverse.html#cb269-1" aria-hidden="true" tabindex="-1"></a>us_rent_income <span class="sc">%&gt;%</span></span>
<span id="cb269-2"><a href="tidyverse.html#cb269-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> variable, <span class="at">values_from =</span> <span class="fu">c</span>(estimate, moe))</span></code></pre></div>
<pre><code>## # A tibble: 52 × 6
##    GEOID NAME                 estimate_income estimate_rent moe_income moe_rent
##    &lt;chr&gt; &lt;chr&gt;                          &lt;dbl&gt;         &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;
##  1 01    Alabama                        24476           747        136        3
##  2 02    Alaska                         32940          1200        508       13
##  3 04    Arizona                        27517           972        148        4
##  4 05    Arkansas                       23789           709        165        5
##  5 06    California                     29454          1358        109        3
##  6 08    Colorado                       32401          1125        109        5
##  7 09    Connecticut                    35326          1123        195        5
##  8 10    Delaware                       31560          1076        247       10
##  9 11    District of Columbia           43198          1424        681       17
## 10 12    Florida                        25952          1077         70        3
## # … with 42 more rows</code></pre>
<p>Adicionalmente, se puede especificar una funcion de agregacion que operara antes de acomodar los datos en las respectivas columnas indicadas. Un ejemplo de funciones agregadas en la reestructuración de tabla se muestra a continuación, donde se muestra la media de los valores en las categorías <em>tension</em> y <em>breaks</em>.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="tidyverse.html#cb271-1" aria-hidden="true" tabindex="-1"></a>warpbreaks <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(warpbreaks[<span class="fu">c</span>(<span class="st">&quot;wool&quot;</span>, <span class="st">&quot;tension&quot;</span>, <span class="st">&quot;breaks&quot;</span>)])</span>
<span id="cb271-2"><a href="tidyverse.html#cb271-2" aria-hidden="true" tabindex="-1"></a>warpbreaks</span></code></pre></div>
<pre><code>## # A tibble: 54 × 3
##    wool  tension breaks
##    &lt;fct&gt; &lt;fct&gt;    &lt;dbl&gt;
##  1 A     L           26
##  2 A     L           30
##  3 A     L           54
##  4 A     L           25
##  5 A     L           70
##  6 A     L           52
##  7 A     L           51
##  8 A     L           26
##  9 A     L           67
## 10 A     M           18
## # … with 44 more rows</code></pre>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="tidyverse.html#cb273-1" aria-hidden="true" tabindex="-1"></a>warpbreaks <span class="sc">%&gt;%</span></span>
<span id="cb273-2"><a href="tidyverse.html#cb273-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb273-3"><a href="tidyverse.html#cb273-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">names_from =</span> wool,</span>
<span id="cb273-4"><a href="tidyverse.html#cb273-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_from =</span> breaks,</span>
<span id="cb273-5"><a href="tidyverse.html#cb273-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">values_fn =</span> mean</span>
<span id="cb273-6"><a href="tidyverse.html#cb273-6" aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   tension     A     B
##   &lt;fct&gt;   &lt;dbl&gt; &lt;dbl&gt;
## 1 L        44.6  28.2
## 2 M        24    28.8
## 3 H        24.6  18.8</code></pre>
</div>
<div id="pivote-vertical" class="section level3" number="9.3.2">
<h3><span class="header-section-number">9.3.2</span> Pivote vertical</h3>
<p><em>pivot_longer()</em> es podría ser la función inversa de la anterior, se necesita comúnmente para ordenar los conjuntos de datos capturados en crudo, ya que a menudo no son capturados a corde a las mejores estructuras para facilitar el análisis.</p>
<p>El conjunto de datos <em>relig_income</em> almacena recuentos basados en una encuesta que (entre otras cosas) preguntó a las personas sobre su religión e ingresos anuales:</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="tidyverse.html#cb275-1" aria-hidden="true" tabindex="-1"></a>relig_income</span></code></pre></div>
<pre><code>## # A tibble: 18 × 11
##    religion `&lt;$10k` `$10-20k` `$20-30k` `$30-40k` `$40-50k` `$50-75k` `$75-100k`
##    &lt;chr&gt;      &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;      &lt;dbl&gt;
##  1 Agnostic      27        34        60        81        76       137        122
##  2 Atheist       12        27        37        52        35        70         73
##  3 Buddhist      27        21        30        34        33        58         62
##  4 Catholic     418       617       732       670       638      1116        949
##  5 Don’t k…      15        14        15        11        10        35         21
##  6 Evangel…     575       869      1064       982       881      1486        949
##  7 Hindu          1         9         7         9        11        34         47
##  8 Histori…     228       244       236       238       197       223        131
##  9 Jehovah…      20        27        24        24        21        30         15
## 10 Jewish        19        19        25        25        30        95         69
## 11 Mainlin…     289       495       619       655       651      1107        939
## 12 Mormon        29        40        48        51        56       112         85
## 13 Muslim         6         7         9        10         9        23         16
## 14 Orthodox      13        17        23        32        32        47         38
## 15 Other C…       9         7        11        13        13        14         18
## 16 Other F…      20        33        40        46        49        63         46
## 17 Other W…       5         2         3         4         2         7          3
## 18 Unaffil…     217       299       374       365       341       528        407
## # … with 3 more variables: `$100-150k` &lt;dbl&gt;, `&gt;150k` &lt;dbl&gt;,
## #   `Don&#39;t know/refused` &lt;dbl&gt;</code></pre>
<p>¿Crees que ésta es la mejor estructura para la tabla? ¿Cómo imaginas que podría mofificarse?</p>
<p>Este conjunto de datos contiene tres variables:</p>
<ol style="list-style-type: decimal">
<li><p>religion, almacenada en las filas</p></li>
<li><p>income repartidos entre los nombres de columna</p></li>
<li><p>count almacenado en los valores de las celdas.</p></li>
</ol>
<p>Para ordenarlo usamos <em>pivot_longer()</em>:</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="tidyverse.html#cb277-1" aria-hidden="true" tabindex="-1"></a>relig_income <span class="sc">%&gt;%</span> </span>
<span id="cb277-2"><a href="tidyverse.html#cb277-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>religion, <span class="at">names_to =</span> <span class="st">&quot;income&quot;</span>, <span class="at">values_to =</span> <span class="st">&quot;count&quot;</span>)</span></code></pre></div>
<pre><code>## # A tibble: 180 × 3
##    religion income             count
##    &lt;chr&gt;    &lt;chr&gt;              &lt;dbl&gt;
##  1 Agnostic &lt;$10k                 27
##  2 Agnostic $10-20k               34
##  3 Agnostic $20-30k               60
##  4 Agnostic $30-40k               81
##  5 Agnostic $40-50k               76
##  6 Agnostic $50-75k              137
##  7 Agnostic $75-100k             122
##  8 Agnostic $100-150k            109
##  9 Agnostic &gt;150k                 84
## 10 Agnostic Don&#39;t know/refused    96
## # … with 170 more rows</code></pre>
<ul>
<li>El primer argumento es el conjunto de datos para remodelar, relig_income.</li>
<li>El segundo argumento describe qué columnas necesitan ser reformadas. En este caso, es cada columna aparte de religion.</li>
<li>El <strong>names_to</strong> da el nombre de la variable que se creará a partir de los datos almacenados en los nombres de columna, es decir, ingresos.</li>
<li>Los <strong>values_to</strong> dan el nombre de la variable que se creará a partir de los datos almacenados en el valor de la celda, es decir, count. Ni la columna names_to ni la values_to existen en relig_income, por lo que las proporcionamos como cadenas de caracteres entre comillas.</li>
</ul>
</div>
<div id="unión-de-columnas" class="section level3" number="9.3.3">
<h3><span class="header-section-number">9.3.3</span> Unión de columnas</h3>
<p>Es común que en los conjuntos de datos exista información esparcida en distintas columas que sería deseable <strong>(en muy pocas ocasiones)</strong> tenerlas en una sola columna. Algunos ejemplos de esta situación deseable son las fechas y claves geoestadísticas. La función <em>unite()</em> sirve para <strong>concatenar el contenido de columnas</strong> mediante un separador elegible.</p>
<p>Se usará la variable de la clave geoestadística de localidades del país como ejemplo.</p>
<p>El formato para las claves geoestadísticas para estado, municipio y localidad son claves alfanuméricas que contienen 2, 3 y 4 caracteres respectivamente. Es indispensable que al trabajar con claves geoestadísticas, las claves estén en su formato original. A continuación se hará la homologación de las claves para usar la función <em>unite()</em>.</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="tidyverse.html#cb279-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(magrittr)</span>
<span id="cb279-2"><a href="tidyverse.html#cb279-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb279-3"><a href="tidyverse.html#cb279-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb279-4"><a href="tidyverse.html#cb279-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb279-5"><a href="tidyverse.html#cb279-5" aria-hidden="true" tabindex="-1"></a>Datos <span class="ot">&lt;-</span> <span class="fu">read_excel</span>(<span class="st">&quot;data/Margin CONAPO.xlsx&quot;</span>, <span class="at">sheet =</span> <span class="st">&quot;Margin CONAPO&quot;</span>)</span>
<span id="cb279-6"><a href="tidyverse.html#cb279-6" aria-hidden="true" tabindex="-1"></a>Datos</span></code></pre></div>
<pre><code>## # A tibble: 107,458 × 21
##      ENT NOM_ENT         MUN NOM_MUN   LOC NOM_LOC POB_TOT    VPH ANAL10 SPRIM10
##    &lt;dbl&gt; &lt;chr&gt;         &lt;dbl&gt; &lt;chr&gt;   &lt;dbl&gt; &lt;chr&gt;     &lt;dbl&gt;  &lt;dbl&gt;  &lt;dbl&gt;   &lt;dbl&gt;
##  1     1 Aguascalient…     1 Aguasc…     1 Aguasc…  722250 184123   2.26   10.9 
##  2     1 Aguascalient…     1 Aguasc…    96 Agua A…      37     11  17.9    48.1 
##  3     1 Aguascalient…     1 Aguasc…   104 Ardill…      14      3   0      20   
##  4     1 Aguascalient…     1 Aguasc…   106 Arella…    1382    255   5.60   24.7 
##  5     1 Aguascalient…     1 Aguasc…   112 Bajío …      55     11  14.3    38.1 
##  6     1 Aguascalient…     1 Aguasc…   114 Reside…     757    202   0       1.63
##  7     1 Aguascalient…     1 Aguasc…   120 Buenav…     935    217  10.7    29.5 
##  8     1 Aguascalient…     1 Aguasc…   121 Cabeci…     184     44   4.55   32.6 
##  9     1 Aguascalient…     1 Aguasc…   125 Cañada…     395     82   8.86   23.9 
## 10     1 Aguascalient…     1 Aguasc…   126 Cañada…     509    123   4.75   19.6 
## # … with 107,448 more rows, and 11 more variables: SEXC10 &lt;dbl&gt;, SEE10 &lt;dbl&gt;,
## #   SAGUAE10 &lt;dbl&gt;, PROM_OCC10 &lt;dbl&gt;, PISOTIE10 &lt;dbl&gt;, SREFRI10 &lt;dbl&gt;,
## #   IM_2010 &lt;dbl&gt;, GM_2010 &lt;chr&gt;, IMC0A100 &lt;dbl&gt;, LUG_NAL &lt;dbl&gt;, LUG_EDO &lt;dbl&gt;</code></pre>
<p>Como puede apreciarse en la tabla anterior, las claves de los campos <em>Ent</em>, <em>Mun</em> y <em>Loc</em> aparecen como numéricos. La estructura deseada para estos campos es de tipo alfanumérico y de longitud 2, 3 y 4 respectivamente. Para lograr esta estructura de datos, es necesario concatenar tantos ceros como sean necesarios antes del valor actual hasta lograr la longitud deseada.</p>
<div class="sourceCode" id="cb281"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb281-1"><a href="tidyverse.html#cb281-1" aria-hidden="true" tabindex="-1"></a>Datos2 <span class="ot">&lt;-</span> Datos <span class="sc">%&gt;%</span> <span class="fu">select</span>(ENT, MUN, LOC)</span>
<span id="cb281-2"><a href="tidyverse.html#cb281-2" aria-hidden="true" tabindex="-1"></a>Datos2<span class="sc">$</span>ENT <span class="sc">%&lt;&gt;%</span> <span class="fu">str_pad</span>(<span class="at">width =</span> <span class="dv">2</span>, <span class="at">side =</span> <span class="st">&quot;left&quot;</span>, <span class="at">pad =</span> <span class="st">&quot;0&quot;</span>)</span>
<span id="cb281-3"><a href="tidyverse.html#cb281-3" aria-hidden="true" tabindex="-1"></a>Datos2<span class="sc">$</span>MUN <span class="sc">%&lt;&gt;%</span> <span class="fu">str_pad</span>(<span class="at">width =</span> <span class="dv">3</span>, <span class="at">side =</span> <span class="st">&quot;left&quot;</span>, <span class="at">pad =</span> <span class="st">&quot;0&quot;</span>)</span>
<span id="cb281-4"><a href="tidyverse.html#cb281-4" aria-hidden="true" tabindex="-1"></a>Datos2<span class="sc">$</span>LOC <span class="sc">%&lt;&gt;%</span> <span class="fu">str_pad</span>(<span class="at">width =</span> <span class="dv">4</span>, <span class="at">side =</span> <span class="st">&quot;left&quot;</span>, <span class="at">pad =</span> <span class="st">&quot;0&quot;</span>)</span>
<span id="cb281-5"><a href="tidyverse.html#cb281-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb281-6"><a href="tidyverse.html#cb281-6" aria-hidden="true" tabindex="-1"></a>Datos2 <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 3
##   ENT   MUN   LOC  
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
## 1 01    001   0001 
## 2 01    001   0096 
## 3 01    001   0104 
## 4 01    001   0106 
## 5 01    001   0112 
## 6 01    001   0114</code></pre>
<div class="sourceCode" id="cb283"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb283-1"><a href="tidyverse.html#cb283-1" aria-hidden="true" tabindex="-1"></a>Datos2 <span class="sc">%&gt;%</span> <span class="fu">unite</span>(<span class="st">&quot;CVE_GEO&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;ENT&quot;</span>,<span class="st">&quot;MUN&quot;</span>,<span class="st">&quot;LOC&quot;</span>), <span class="at">sep=</span><span class="st">&quot;&quot;</span>, <span class="at">remove =</span> F) <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   CVE_GEO   ENT   MUN   LOC  
##   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
## 1 010010001 01    001   0001 
## 2 010010096 01    001   0096 
## 3 010010104 01    001   0104 
## 4 010010106 01    001   0106 
## 5 010010112 01    001   0112 
## 6 010010114 01    001   0114</code></pre>
<div class="sourceCode" id="cb285"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb285-1"><a href="tidyverse.html#cb285-1" aria-hidden="true" tabindex="-1"></a>Datos2 <span class="sc">%&gt;%</span> <span class="fu">unite</span>(<span class="st">&quot;CVE_GEO&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;ENT&quot;</span>,<span class="st">&quot;MUN&quot;</span>,<span class="st">&quot;LOC&quot;</span>), <span class="at">sep=</span><span class="st">&quot;/&quot;</span>,<span class="at">remove =</span> T) <span class="sc">%&gt;%</span> <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 1
##   CVE_GEO    
##   &lt;chr&gt;      
## 1 01/001/0001
## 2 01/001/0096
## 3 01/001/0104
## 4 01/001/0106
## 5 01/001/0112
## 6 01/001/0114</code></pre>
<p>En el código anterior se carga la librería <em>magrittr</em> para poder hacer uso del operador pipe doble “%&lt;&gt;%,” que permite al igual que el operador pipe simple “%&gt;%,” usar como argumento al primer elemento y mandarlo hacia la función definida, además de guardar el resultado final de la cadena de pipes en el argumento original que fue usado como insumo para la función. Es importante tener en cuenta que el dato será reescrito y no se podrá tener acceso a su información almacenada antes de ser usado el operador.</p>
<p>Es opción del programador poder eliminar las variables originales que crearon la nueva variable o mantenerlas en el conjunto de datos. Esta opción está disponible en el parámetro <em>remove</em> de la función <em>unite()</em>.</p>
</div>
<div id="separador-de-columnas" class="section level3" number="9.3.4">
<h3><span class="header-section-number">9.3.4</span> Separador de columnas</h3>
<p>Los procesos que se han visto hasta ahora han tenido cada uno una función inversa, este es también el caso de la función <em>unite</em> que tiene por objetivo unir dos o más columnas en una. La función <em>separate()</em> separará una columna en dos o más dependiendo de la longitud que tenga y de las especificaciones de separación.</p>
<div class="sourceCode" id="cb287"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb287-1"><a href="tidyverse.html#cb287-1" aria-hidden="true" tabindex="-1"></a>Datos_unite1 <span class="ot">&lt;-</span> Datos2 <span class="sc">%&gt;%</span> <span class="fu">unite</span>(<span class="st">&quot;CVE_GEO&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;ENT&quot;</span>,<span class="st">&quot;MUN&quot;</span>,<span class="st">&quot;LOC&quot;</span>), <span class="at">sep =</span> <span class="st">&quot;&quot;</span>, <span class="at">remove =</span> T) </span>
<span id="cb287-2"><a href="tidyverse.html#cb287-2" aria-hidden="true" tabindex="-1"></a>Datos_unite1 <span class="sc">%&gt;%</span> <span class="fu">head</span>() </span></code></pre></div>
<pre><code>## # A tibble: 6 × 1
##   CVE_GEO  
##   &lt;chr&gt;    
## 1 010010001
## 2 010010096
## 3 010010104
## 4 010010106
## 5 010010112
## 6 010010114</code></pre>
<div class="sourceCode" id="cb289"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb289-1"><a href="tidyverse.html#cb289-1" aria-hidden="true" tabindex="-1"></a>Datos_unite1 <span class="sc">%&gt;%</span> </span>
<span id="cb289-2"><a href="tidyverse.html#cb289-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">separate</span>(<span class="st">&quot;CVE_GEO&quot;</span>, <span class="fu">c</span>(<span class="st">&quot;EDO&quot;</span>,<span class="st">&quot;MUNI&quot;</span>,<span class="st">&quot;LOC&quot;</span>), <span class="at">sep =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">5</span>), <span class="at">remove=</span>F) <span class="sc">%&gt;%</span> </span>
<span id="cb289-3"><a href="tidyverse.html#cb289-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">head</span>()</span></code></pre></div>
<pre><code>## # A tibble: 6 × 4
##   CVE_GEO   EDO   MUNI  LOC  
##   &lt;chr&gt;     &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
## 1 010010001 01    001   0001 
## 2 010010096 01    001   0096 
## 3 010010104 01    001   0104 
## 4 010010106 01    001   0106 
## 5 010010112 01    001   0112 
## 6 010010114 01    001   0114</code></pre>
<p>Ya sea que se le especifique el número de caracteres que debe de contar para hacer un corte o que se le indique qué caracter debe identificar para hacer la separación, la función <em>separate()</em> puede dividir la columna indicada y crear nuevas a partir de la original.</p>
</div>
</div>
<div id="manipulación-de-texto-stringr" class="section level2" number="9.4">
<h2><span class="header-section-number">9.4</span> Manipulación de texto (stringr)</h2>
<p>Anteriormente se mencionaron algunas paqueterías que están incluídas dentro del conjunto Tidyverse. La paquetería stringr no forma parte del núcleo de Tidyverse, no obstante, sí pertenece a dicho conjunto y es ampliamente usada junto a las paqueterías nucleares debido a la facilidad que tiene para trabajar con cadenas, textos y espresiones regulares en general. Las expresiones regulares, también conocidas como <em>regex</em> o <em>regexp</em>, <strong>son patrones de texto repetidos en los datos y que son usados para operar con otras cadenas de texto</strong>. El resultado de dichas operaciones es obtener o resumir información, además de manipular y ordenar los conjuntos de datos. Entre las principales operaciones se encuentran los conteos, concatenaciones, separaciones, búsquedas, extracciones, imputaciones y sustituciones.</p>
<div id="caracteres-especiales" class="section level3" number="9.4.1">
<h3><span class="header-section-number">9.4.1</span> Caracteres especiales</h3>
<p>Debido a que la paquetería <em>stringr</em> trabaja principalmente con cadenas de texto, es importante tener en cuenta que <strong>los objetos de caracteres se definen a través de comillas</strong>, ya sea simples o dobles. La única diferencia está en el caso en que se pretendan usar comillas como parte del texto. En estos casos, la comilla simple es preferible para ser la que defina el texto.</p>
<div class="sourceCode" id="cb291"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb291-1"><a href="tidyverse.html#cb291-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stringr)</span>
<span id="cb291-2"><a href="tidyverse.html#cb291-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb291-3"><a href="tidyverse.html#cb291-3" aria-hidden="true" tabindex="-1"></a>Cadena1 <span class="ot">&lt;-</span> <span class="st">&quot;Se definen cadenas a través de comillas dobles&quot;</span></span>
<span id="cb291-4"><a href="tidyverse.html#cb291-4" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Cadena1)</span></code></pre></div>
<pre><code>## [1] &quot;Se definen cadenas a través de comillas dobles&quot;</code></pre>
<div class="sourceCode" id="cb293"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb293-1"><a href="tidyverse.html#cb293-1" aria-hidden="true" tabindex="-1"></a>Cadena2 <span class="ot">&lt;-</span> <span class="st">&#39;También es posible con comillas simples y el resultado es el mismo&#39;</span></span>
<span id="cb293-2"><a href="tidyverse.html#cb293-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Cadena2)</span></code></pre></div>
<pre><code>## [1] &quot;También es posible con comillas simples y el resultado es el mismo&quot;</code></pre>
<div class="sourceCode" id="cb295"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb295-1"><a href="tidyverse.html#cb295-1" aria-hidden="true" tabindex="-1"></a>Cadena3 <span class="ot">&lt;-</span> <span class="st">&#39;Se pueden implementar &quot;comillas&quot; dentro de la cadena&#39;</span></span>
<span id="cb295-2"><a href="tidyverse.html#cb295-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Cadena3)</span></code></pre></div>
<pre><code>## [1] &quot;Se pueden implementar \&quot;comillas\&quot; dentro de la cadena&quot;</code></pre>
<div class="sourceCode" id="cb297"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb297-1"><a href="tidyverse.html#cb297-1" aria-hidden="true" tabindex="-1"></a>Cadena4 <span class="ot">&lt;-</span> <span class="st">&#39;Esta es otra forma de incluir </span><span class="sc">\&quot;</span><span class="st">comillas</span><span class="sc">\&quot;</span><span class="st"> dentro de un texto&#39;</span></span>
<span id="cb297-2"><a href="tidyverse.html#cb297-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(Cadena4)</span></code></pre></div>
<pre><code>## [1] &quot;Esta es otra forma de incluir \&quot;comillas\&quot; dentro de un texto&quot;</code></pre>
<p>Como es posible apreciar en los ejemplos anteriores, la cadena 3 y 4 no se imprimen exactamente como se definieron. Podría parecer que existe un error, ya que aparecen diagonales antes de los caracteres deseados. Para resolver este problema, únicamente es necesario mandar llamar a la función <em>cat()</em> . Esta función sirve como intérprete de los caracteres que se definen en una cadena.</p>
<p>La función <em>cat()</em> <strong>sirve como sustituto</strong> de la función <em>print()</em> (cuya función es imprimir de forma literal lo que existe dentro de las comillas), con la diferencia de que <em>cat()</em> <strong>interpreta las salidas</strong> de caracteres especiales en el texto y concatena las salidas finales con el separador específico que se indique. Por default, el separador es un espacio vacío, sin embargo, es posible modificarlo. A continuación se ejemplifica su uso.</p>
<div class="sourceCode" id="cb299"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb299-1"><a href="tidyverse.html#cb299-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(Cadena3)</span></code></pre></div>
<pre><code>## Se pueden implementar &quot;comillas&quot; dentro de la cadena</code></pre>
<div class="sourceCode" id="cb301"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb301-1"><a href="tidyverse.html#cb301-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(Cadena4)</span></code></pre></div>
<pre><code>## Esta es otra forma de incluir &quot;comillas&quot; dentro de un texto</code></pre>
<p>A través del operador diagonal invertida “\” también es posible definir comillas de manera literal. En caso de querer escribir textualmente una diagonal invertida, se necesitará escribir entre comillas dos diagonales invertidas “\\.” Existen otros caracteres espaciales que ayudan a mejorar el formato de las cadenas. Algunos de los caracteres más comunes son “\n” (nueva línea) y “\t” (tabulador).</p>
<p>Todas las funciones que se presentarán a continuación, son posibles encontrarlas con otro nombre dentro de la paquetería básica. La ventaja que tienen las funciones de la paquetería <em>stringr</em> es que, los nombres son más intuitivos y comienzan con el mismo prefijo “str_,” haciendo que al escribir las primeras tres letras, la función de autocompletar de RStudio muestre una lista con sugerencias de los nombres de las posibles funciones a usarse.</p>
</div>
<div id="tamaño-de-la-cadena" class="section level3" number="9.4.2">
<h3><span class="header-section-number">9.4.2</span> Tamaño de la cadena</h3>
<p>Es común que al procesar los conjuntos de datos, se requiera contar el número de caracteres que tiene una cadena. La paquetería básica cuenta con la función <em>nchar()</em> para realizar esta tarea. Con la ayuda de la paquetería <em>stringr</em>, es posible realizar esta misma tarea a través de la función <em>str_length()</em></p>
<div class="sourceCode" id="cb303"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb303-1"><a href="tidyverse.html#cb303-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_length</span>(<span class="st">&quot;Esta es una cadena de 35 caracteres&quot;</span>)</span></code></pre></div>
<pre><code>## [1] 35</code></pre>
<div class="sourceCode" id="cb305"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb305-1"><a href="tidyverse.html#cb305-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_length</span>(<span class="fu">c</span>(<span class="st">&quot;Un&quot;</span>,<span class="st">&quot;vector&quot;</span>,<span class="st">&quot;con&quot;</span>,<span class="st">&quot;diferente&quot;</span>,<span class="st">&quot;cantidad&quot;</span>,<span class="st">&quot;de&quot;</span>,<span class="st">&quot;carecteres&quot;</span>,<span class="st">&quot;por&quot;</span>,<span class="st">&quot;cadena&quot;</span>))</span></code></pre></div>
<pre><code>## [1]  2  6  3  9  8  2 10  3  6</code></pre>
<p>Puede usarse la función tanto para objetos de cadenas individuales como para vectores.</p>
<p>Existen muchos conjuntos de datos que durante su manipulacion podemos encontrar claves alfanuméricas, que pueden ser necesarias <strong>unir información</strong> relevante o para crear claves de identificación única, por ejemplo poder unir el nombre completo de las personas dentro de una base de datos. Uniendo Nombre + Segundo Nombre + Primer Apellido + Segundo Apellido.</p>
<p>Por otro lado de esto puede extraerse información sobre la CURP o en algunos otros ejemplos la unión de un ID + una matricula de carrera + el año pueden ser el registro para un estudiante ó podrias querer replicar mensajes para alertas que dependan de una variable.</p>
</div>
<div id="concatenar-cadenas" class="section level3" number="9.4.3">
<h3><span class="header-section-number">9.4.3</span> Concatenar cadenas</h3>
<p>Concatenar cadenas es una de las prácticas constantes en el manejo de conjuntos de datos. La función de la paquetería básica que se encarga de dicha tarea es la función <em>paste()</em>. A través de la paquetería <em>stringr</em> se logrará el <strong>concatenado</strong> mediante la función <em>str_c()</em>. Existe la opción de definir el caracter que hará la combinación de las cadenas mediante el argumento “sep,” que por default no deja ni un espacio entre las cadenas a combinar. Varios ejemplos se mostrarán a continuación.</p>
<div class="sourceCode" id="cb307"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb307-1"><a href="tidyverse.html#cb307-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_c</span>(<span class="st">&quot;Concatenado&quot;</span>, <span class="st">&quot;de&quot;</span>,<span class="st">&quot;varias&quot;</span>, <span class="st">&quot;cadenas&quot;</span>, <span class="st">&quot;sin&quot;</span>,<span class="st">&quot;espacios&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Concatenadodevariascadenassinespacios&quot;</code></pre>
<div class="sourceCode" id="cb309"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb309-1"><a href="tidyverse.html#cb309-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_c</span>(<span class="st">&quot;Concatenado&quot;</span>,<span class="st">&quot;con&quot;</span>,<span class="st">&quot;espacios&quot;</span>, <span class="at">sep=</span><span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Concatenado con espacios&quot;</code></pre>
<div class="sourceCode" id="cb311"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb311-1"><a href="tidyverse.html#cb311-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_c</span>(<span class="st">&quot;separando&quot;</span>,<span class="st">&quot;mediante&quot;</span>,<span class="st">&quot;otro&quot;</span>,<span class="st">&quot;caracter&quot;</span>,<span class="st">&quot;definido&quot;</span>, <span class="at">sep=</span><span class="st">&quot;-&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;separando-mediante-otro-caracter-definido&quot;</code></pre>
<div class="sourceCode" id="cb313"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb313-1"><a href="tidyverse.html#cb313-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_c</span>(<span class="st">&quot;Valores&quot;</span>,<span class="fu">str_c</span>(<span class="st">&quot;09&quot;</span>,<span class="st">&quot;006&quot;</span>),<span class="st">&quot;anidados también se pueden concatenar&quot;</span>,<span class="at">sep=</span><span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Valores 09006 anidados también se pueden concatenar&quot;</code></pre>
<p>Es posible, al igual que con la función <em>paste()</em>, colapsar todas las cadenas de un vector en una sola cadena mediante el mismo parámetro: “collapse.” El caracter que divide a los elementos del vector debe ser especificado entre comillas, de lo contrario el valor por default será " ".</p>
<div class="sourceCode" id="cb315"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb315-1"><a href="tidyverse.html#cb315-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_c</span>(<span class="fu">c</span>(<span class="st">&quot;Colapsamiento&quot;</span>, <span class="st">&quot;de&quot;</span>,<span class="st">&quot;un&quot;</span>,<span class="st">&quot;vector&quot;</span>,<span class="st">&quot;de&quot;</span>, <span class="st">&quot;cadenas&quot;</span>, <span class="st">&quot;en&quot;</span>,<span class="st">&quot;una&quot;</span>,</span>
<span id="cb315-2"><a href="tidyverse.html#cb315-2" aria-hidden="true" tabindex="-1"></a>        <span class="st">&quot;sola&quot;</span>,<span class="st">&quot;cadena&quot;</span>), <span class="at">collapse =</span> <span class="st">&quot; &quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Colapsamiento de un vector de cadenas en una sola cadena&quot;</code></pre>
<div class="sourceCode" id="cb317"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb317-1"><a href="tidyverse.html#cb317-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_c</span>(<span class="fu">c</span>(<span class="st">&quot;Colapsamiento&quot;</span>, <span class="st">&quot;de&quot;</span>,<span class="st">&quot;un&quot;</span>,<span class="st">&quot;vector&quot;</span>,<span class="st">&quot;de&quot;</span>, <span class="st">&quot;cadenas&quot;</span>,</span>
<span id="cb317-2"><a href="tidyverse.html#cb317-2" aria-hidden="true" tabindex="-1"></a>        <span class="st">&quot;separado&quot;</span>,<span class="st">&quot;por&quot;</span>,<span class="st">&quot;signos&quot;</span>), <span class="at">collapse =</span> <span class="st">&quot;+&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;Colapsamiento+de+un+vector+de+cadenas+separado+por+signos&quot;</code></pre>
</div>
<div id="extraer-y-reemplazar-subcadenas" class="section level3" number="9.4.4">
<h3><span class="header-section-number">9.4.4</span> Extraer y reemplazar subcadenas</h3>
<p>Cuando únicamente interesa un <strong>subconjunto de alguna cadena</strong> para continuar con el manejo de la información, suele recurrirse a la expresión regular <em>substr()</em> de la paquetería básica para extraer este subconjunto de interés. Con <em>stringr</em>, la función para usar esta expresión regular es <em>str_sub()</em>. Esta función recibe como parámetros el texto desde el cuál se desea extraer el subconjunto, el índice que marque el inicio de la subcadena y el índice del final de la subcadena.</p>
<div class="sourceCode" id="cb319"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb319-1"><a href="tidyverse.html#cb319-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_sub</span>(<span class="st">&quot;subcadenas&quot;</span>, <span class="at">start =</span> <span class="dv">4</span>, <span class="at">end =</span> <span class="dv">9</span>)</span></code></pre></div>
<pre><code>## [1] &quot;cadena&quot;</code></pre>
<div class="sourceCode" id="cb321"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb321-1"><a href="tidyverse.html#cb321-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="st">&quot;00000090060002&quot;</span></span>
<span id="cb321-2"><a href="tidyverse.html#cb321-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str_sub</span>(x, <span class="at">start =</span> <span class="fu">str_length</span>(x) <span class="sc">-</span> <span class="dv">8</span>, <span class="fu">str_length</span>(x))</span></code></pre></div>
<pre><code>## [1] &quot;090060002&quot;</code></pre>
<div class="sourceCode" id="cb323"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb323-1"><a href="tidyverse.html#cb323-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_sub</span>(x, <span class="at">start =</span> <span class="sc">-</span><span class="dv">9</span>)</span></code></pre></div>
<pre><code>## [1] &quot;090060002&quot;</code></pre>
<p>Con la misma función <em>str_sub()</em> es posible <strong>sustituir parcial o totalmente</strong> la cadena “X” que sea introducida como argumento. Ésto se logra asignando a la subcadena seleccionada el valor que se usará para sustituir. En los siguientes ejemplos se muestra cómo modificar la cadena “substring” y la cadena “090060002.”</p>
<p>En el primer caso, a partir de la cadena de caracteres “substring” se procede a generar una nueva cadena al sustituir las letras 4 a la 9, reemplazando así la subcadena “string” por “cadena,” dando lugar a “subcadena.” En el segundo ejemplo, es la clave correspondiente a los dígitos 3 a 5 los que cambian para dar lugar a otra clave numérica.</p>
<div class="sourceCode" id="cb325"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb325-1"><a href="tidyverse.html#cb325-1" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="st">&quot;substring&quot;</span></span>
<span id="cb325-2"><a href="tidyverse.html#cb325-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str_sub</span>(y, <span class="at">start =</span> <span class="dv">4</span>, <span class="at">end =</span> <span class="dv">9</span>) <span class="ot">&lt;-</span> <span class="st">&quot;cadena&quot;</span>; y</span></code></pre></div>
<pre><code>## [1] &quot;subcadena&quot;</code></pre>
<div class="sourceCode" id="cb327"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb327-1"><a href="tidyverse.html#cb327-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="st">&quot;090060002&quot;</span></span>
<span id="cb327-2"><a href="tidyverse.html#cb327-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str_sub</span>(x, <span class="at">start =</span> <span class="fu">str_length</span>(x)<span class="sc">-</span><span class="dv">6</span>,<span class="fu">str_length</span>(x)<span class="sc">-</span><span class="dv">4</span>) <span class="ot">&lt;-</span> <span class="st">&quot;555&quot;</span>; x </span></code></pre></div>
<pre><code>## [1] &quot;095550002&quot;</code></pre>
<p>Lo anterior es ampliamente usado en el proceso de limpieza de los datos. A veces es posible encontrar errores ortográficos o los llamados errores “de dedo” (hacen referencia a errores accidentales al escribir) que se dan a la hora de capturar la información. Cuando una gran cantidad de datos presentan el mismo error, es buena idea recurrir a esta función.</p>
</div>
<div id="expresiones-regulares" class="section level3" number="9.4.5">
<h3><span class="header-section-number">9.4.5</span> Expresiones regulares</h3>
<p>En el estudio de las expresiones regulares se puede encontrar de manera sobresaliente la aplicación de los <em>patrones coincidentes</em>, los cuáles sirven para describir y descubrir coincidencias de interés en conjuntos específicos a partir de cadenas de caracteres.</p>
<p>Con el fin de comprender y visualizar de manera práctica el uso de los patrones coincidentes con las expresiones regulares, se hará uso de la función <em>str_view()</em>, que permite distinguir los elementos coincidentes de un vector con un patrón de caracteres descrito.</p>
<p>La paquetería <em>stringr</em> cuenta con tres conjuntos predefinidos de oraciones y palabras que sirven para ejemplificar el uso de las expresiones regulares. Estos conjuntos llevan el nombre de <strong>sentences, words y fruit</strong>, su contenido es de sentencias, palabras y nombres de frutas. En los tres casos, estos conjuntos han sido escritos en inglés. Los conjuntos sirven bien para ejemplificar el uso de las siguientes funciones y de las expresiones regulares.</p>
<div class="sourceCode" id="cb329"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb329-1"><a href="tidyverse.html#cb329-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(sentences, <span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;The birch canoe slid on the smooth planks.&quot; 
##  [2] &quot;Glue the sheet to the dark blue background.&quot;
##  [3] &quot;It&#39;s easy to tell the depth of a well.&quot;     
##  [4] &quot;These days a chicken leg is a rare dish.&quot;   
##  [5] &quot;Rice is often served in round bowls.&quot;       
##  [6] &quot;The juice of lemons makes fine punch.&quot;      
##  [7] &quot;The box was thrown beside the parked truck.&quot;
##  [8] &quot;The hogs were fed chopped corn and garbage.&quot;
##  [9] &quot;Four hours of steady work faced us.&quot;        
## [10] &quot;Large size in stockings is hard to sell.&quot;</code></pre>
<div class="sourceCode" id="cb331"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb331-1"><a href="tidyverse.html#cb331-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(words, <span class="dv">20</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;a&quot;         &quot;able&quot;      &quot;about&quot;     &quot;absolute&quot;  &quot;accept&quot;    &quot;account&quot;  
##  [7] &quot;achieve&quot;   &quot;across&quot;    &quot;act&quot;       &quot;active&quot;    &quot;actual&quot;    &quot;add&quot;      
## [13] &quot;address&quot;   &quot;admit&quot;     &quot;advertise&quot; &quot;affect&quot;    &quot;afford&quot;    &quot;after&quot;    
## [19] &quot;afternoon&quot; &quot;again&quot;</code></pre>
<div class="sourceCode" id="cb333"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb333-1"><a href="tidyverse.html#cb333-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(fruit, <span class="dv">20</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;apple&quot;        &quot;apricot&quot;      &quot;avocado&quot;      &quot;banana&quot;       &quot;bell pepper&quot; 
##  [6] &quot;bilberry&quot;     &quot;blackberry&quot;   &quot;blackcurrant&quot; &quot;blood orange&quot; &quot;blueberry&quot;   
## [11] &quot;boysenberry&quot;  &quot;breadfruit&quot;   &quot;canary melon&quot; &quot;cantaloupe&quot;   &quot;cherimoya&quot;   
## [16] &quot;cherry&quot;       &quot;chili pepper&quot; &quot;clementine&quot;   &quot;cloudberry&quot;   &quot;coconut&quot;</code></pre>
<p>Para realizar una coincidencia de patrones, es necesario ingresar como argumento el vector de cadenas de caracteres en donde se desea hacer la búsqueda. Como segundo argumento, se ingresa el patrón con el cuál se desea buscar las coincidencias. Para que únicamente se muestren las coincidencias exitosas se debe agregar el argumento match = TRUE.</p>
<div class="sourceCode" id="cb335"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb335-1"><a href="tidyverse.html#cb335-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(sentences,<span class="st">&quot;great&quot;</span>, <span class="at">match =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div id="htmlwidget-05ae4a3de23d5cb5503f" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-05ae4a3de23d5cb5503f">{"x":{"html":"<ul>\n  <li>Act on these orders with <span class='match'>great<\/span> speed.<\/li>\n  <li>He knew the skill of the <span class='match'>great<\/span> young actress.<\/li>\n  <li>The aim of the contest is to raise a <span class='match'>great<\/span> fund.<\/li>\n  <li>Seven seals were stamped on <span class='match'>great<\/span> sheets.<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<div class="sourceCode" id="cb336"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb336-1"><a href="tidyverse.html#cb336-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(sentences,<span class="st">&quot;this&quot;</span>, <span class="at">match =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div id="htmlwidget-4e621dc495c29c0c9dee" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-4e621dc495c29c0c9dee">{"x":{"html":"<ul>\n  <li>These <span class='match'>this<\/span>tles bend in a high wind.<\/li>\n  <li>A speedy man can beat <span class='match'>this<\/span> track mark.<\/li>\n  <li>Madam, <span class='match'>this<\/span> is the best brand of corn.<\/li>\n  <li>Dispense with a vest on a day like <span class='match'>this<\/span>.<\/li>\n  <li>The water in <span class='match'>this<\/span> well is a source of good health.<\/li>\n  <li>Take shelter in <span class='match'>this<\/span> tent, but keep still.<\/li>\n  <li>Shake hands with <span class='match'>this<\/span> friendly child.<\/li>\n  <li>A rich farm is rare in <span class='match'>this<\/span> sandy waste.<\/li>\n  <li>Flood the mails with requests for <span class='match'>this<\/span> book.<\/li>\n  <li>Post no bills on <span class='match'>this<\/span> office wall.<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<p>Como es posible apreciarse en los dos ejemplos anteriores, la función <em>str_view()</em> filtra los casos coincidentes con los patrones “great” y “this.” Esta coincidencia no necesariamente es perfecta. Basta con que un subconjunto de la sentencia coincida con el patrón definido para que la función <em>str_view()</em> reconozca como coincidencia válida a toda la cadena.</p>
<p>En caso de no contar con todos los caracteres del patrón deseado o de querer ver todas las combinaciones que tengan un patrón adyacente común, es posible ingresar un “comodín” a través del caracter punto ".", el cuál coincidirá con cualquier caracter. Este caracter especial puede usarse al principio, al final o de manera intermedia dentro del patrón.</p>
<div class="sourceCode" id="cb337"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb337-1"><a href="tidyverse.html#cb337-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(sentences,<span class="st">&quot;up.&quot;</span>, <span class="at">match =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div id="htmlwidget-cf6ccb10836bba95f198" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-cf6ccb10836bba95f198">{"x":{"html":"<ul>\n  <li>The small p<span class='match'>up <\/span>gnawed a hole in the sock.<\/li>\n  <li>A c<span class='match'>up <\/span>of sugar makes sweet fudge.<\/li>\n  <li>The play seems dull and quite st<span class='match'>upi<\/span>d.<\/li>\n  <li>The c<span class='match'>up <\/span>cracked and spilled its contents.<\/li>\n  <li>An abr<span class='match'>upt<\/span> start does not win the prize.<\/li>\n  <li>A rag will soak <span class='match'>up <\/span>spilled water.<\/li>\n  <li>Rake the rubbish <span class='match'>up <\/span>and then burn it.<\/li>\n  <li>He broke his ties with gro<span class='match'>ups<\/span> of former friends.<\/li>\n  <li>Jump the fence and hurry <span class='match'>up <\/span>the bank.<\/li>\n  <li>Women form less than half of the gro<span class='match'>up.<\/span><\/li>\n  <li>Just hoist it <span class='match'>up <\/span>and take it away,<\/li>\n  <li>The sun came <span class='match'>up <\/span>to light the eastern sky.<\/li>\n  <li>Grace makes <span class='match'>up <\/span>for lack of beauty.<\/li>\n  <li>The ramp led <span class='match'>up <\/span>to the wide highway.<\/li>\n  <li>He picked <span class='match'>up <\/span>the dice for a second roll.<\/li>\n  <li>Throw out the used paper c<span class='match'>up <\/span>and plate.<\/li>\n  <li>Footprints showed the path he took <span class='match'>up <\/span>the beach.<\/li>\n  <li>A six comes <span class='match'>up <\/span>more often than a ten.<\/li>\n  <li>The p<span class='match'>up <\/span>jerked the leash as he saw a feline shape.<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<p>Como se puede observar, esta es una manera de detectar subconjuntos de particular interés.</p>
<p><strong>Anclajes</strong></p>
<p>Como se mencionó anteriormente, por default, la coincidencia de patrones se efectuará sobre cualquier subconjunto de la cadena de caracteres. Es posible definir el caracter inicial y/o el caracter final con el cuál se buscará la coincidencia de patrones. Esto se logra al hacer uso de los siguientes caracteres especiales.</p>
<ul>
<li>^ Para hacer coincidir el inicio de la cadena</li>
<li>$ Para hacer coincidir el final de la cadena</li>
</ul>
<div class="sourceCode" id="cb338"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb338-1"><a href="tidyverse.html#cb338-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(words,<span class="st">&quot;^y&quot;</span>, <span class="at">match =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div id="htmlwidget-112dd28b912759ab9078" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-112dd28b912759ab9078">{"x":{"html":"<ul>\n  <li><span class='match'>y<\/span>ear<\/li>\n  <li><span class='match'>y<\/span>es<\/li>\n  <li><span class='match'>y<\/span>esterday<\/li>\n  <li><span class='match'>y<\/span>et<\/li>\n  <li><span class='match'>y<\/span>ou<\/li>\n  <li><span class='match'>y<\/span>oung<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<div class="sourceCode" id="cb339"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb339-1"><a href="tidyverse.html#cb339-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(words,<span class="st">&quot;x$&quot;</span>, <span class="at">match =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<div id="htmlwidget-d64c84362a2199539b68" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-d64c84362a2199539b68">{"x":{"html":"<ul>\n  <li>bo<span class='match'>x<\/span><\/li>\n  <li>se<span class='match'>x<\/span><\/li>\n  <li>si<span class='match'>x<\/span><\/li>\n  <li>ta<span class='match'>x<\/span><\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<p>En caso de desear hacer coincidir todo el contenido de la cadena, deben usarse ambos caracteres especiales para definir el inicio y el final del patrón coincidente como se muestra a continuación.</p>
<div class="sourceCode" id="cb340"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb340-1"><a href="tidyverse.html#cb340-1" aria-hidden="true" tabindex="-1"></a>vector <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;nulo éxito&quot;</span>, <span class="st">&quot;poco éxito&quot;</span>,<span class="st">&quot;éxito moderado&quot;</span>,<span class="st">&quot;éxito&quot;</span>, <span class="st">&quot;éxito total&quot;</span>)</span></code></pre></div>
<div class="sourceCode" id="cb341"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb341-1"><a href="tidyverse.html#cb341-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(vector,<span class="st">&quot;^éxito$&quot;</span>)</span></code></pre></div>
<div id="htmlwidget-a5ed62e546bfa15d6fc4" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-a5ed62e546bfa15d6fc4">{"x":{"html":"<ul>\n  <li>nulo éxito<\/li>\n  <li>poco éxito<\/li>\n  <li>éxito moderado<\/li>\n  <li><span class='match'>éxito<\/span><\/li>\n  <li>éxito total<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<p>Wickham menciona que, además del caracter especial punto ".", existen otros cuatro que resultan muy útiles para mostrar patrones particulares.</p>
<ul>
<li>\d Hace coincidir cualquier dígito.</li>
<li>\s Hace coincidir cualquier espacio en blanco (espacio, tabulador, salto de línea).</li>
<li>[abc] Hace coincidir a, b ó c.</li>
<li>[^abc] Coincide con cualquier cosa excepto a, b ó c.</li>
</ul>
<p>Al momento de definir cualquiera de estos 4 patrones coincidentes será necesario usar doble diagonal invertida. Por ejemplo, “\\d” será el patrón para encontrar la coincidencia con cualquier dígito.</p>
<div class="sourceCode" id="cb342"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb342-1"><a href="tidyverse.html#cb342-1" aria-hidden="true" tabindex="-1"></a>cadena <span class="ot">&lt;-</span> <span class="st">&quot;El año 2018 fue un año de mucho crecimiento personal.&quot;</span></span></code></pre></div>
<div class="sourceCode" id="cb343"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb343-1"><a href="tidyverse.html#cb343-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(cadena,<span class="st">&quot;</span><span class="sc">\\</span><span class="st">d&quot;</span>, <span class="at">match =</span> T)</span></code></pre></div>
<div id="htmlwidget-54bd38e9dafe808fa722" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-54bd38e9dafe808fa722">{"x":{"html":"<ul>\n  <li>El año <span class='match'>2<\/span>018 fue un año de mucho crecimiento personal.<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<p>Wickham menciona que, “es posible usar alternancias para elegir entre uno o más patrones alternativos. Por ejemplo, abc|d..f coincidirá con”abc" o con “deaf.” Haciendo notar que la prioridad para el operador "|" es baja, por lo que abc|xyz coincide con abc o xyz, no con abcyz o abxyz. Al igual que en las matemáticas, si existe ambigüedad en la prioridad de las operaciones, usar paréntesis lo hará todo más claro."</p>
<div class="sourceCode" id="cb344"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb344-1"><a href="tidyverse.html#cb344-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(<span class="fu">c</span>(<span class="st">&quot;tamaño&quot;</span>,<span class="st">&quot;tasa&quot;</span>,<span class="st">&quot;tata&quot;</span>,<span class="st">&quot;taza&quot;</span>,<span class="st">&quot;tapa&quot;</span>),<span class="st">&quot;ta(s|z)a&quot;</span>)</span></code></pre></div>
<div id="htmlwidget-9e4bb4a2048a6b833455" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-9e4bb4a2048a6b833455">{"x":{"html":"<ul>\n  <li>tamaño<\/li>\n  <li><span class='match'>tasa<\/span><\/li>\n  <li>tata<\/li>\n  <li><span class='match'>taza<\/span><\/li>\n  <li>tapa<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<p><strong>Repeticiones</strong></p>
<p>El siguiente paso en complejidad para las expresiones regulares es, controlar el número de veces que aparece un patrón coincidente.</p>
<ul>
<li>?: Se repite 0 o 1.</li>
<li>+: Se repite 1 o más veces.</li>
<li>*: Se repite 0 a más veces.</li>
</ul>
<div class="sourceCode" id="cb345"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb345-1"><a href="tidyverse.html#cb345-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="st">&quot;1888 es el año más largo en números romanos: MDCCCLXXXVIII&quot;</span></span></code></pre></div>
<div class="sourceCode" id="cb346"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb346-1"><a href="tidyverse.html#cb346-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(x,<span class="st">&quot;XX?&quot;</span>)</span></code></pre></div>
<div id="htmlwidget-0f09063e43e87240e862" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-0f09063e43e87240e862">{"x":{"html":"<ul>\n  <li>1888 es el año más largo en números romanos: MDCCCL<span class='match'>XX<\/span>XVIII<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<div class="sourceCode" id="cb347"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb347-1"><a href="tidyverse.html#cb347-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(x,<span class="st">&quot;XX+&quot;</span>)</span></code></pre></div>
<div id="htmlwidget-1fe1198439f1be904d72" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-1fe1198439f1be904d72">{"x":{"html":"<ul>\n  <li>1888 es el año más largo en números romanos: MDCCCL<span class='match'>XXX<\/span>VIII<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<div class="sourceCode" id="cb348"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb348-1"><a href="tidyverse.html#cb348-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(x,<span class="st">&quot;C[LX]+&quot;</span>)</span></code></pre></div>
<div id="htmlwidget-cbf1985aa9cf735da6db" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-cbf1985aa9cf735da6db">{"x":{"html":"<ul>\n  <li>1888 es el año más largo en números romanos: MDCC<span class='match'>CLXXX<\/span>VIII<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<p>Es posible especificar el número de repeticiones que se desea hacer coincidir un patrón. Ya sea de manera exacta o dentro de un intervalo. Esta repetición en el patrón se define de la siguiente manera.</p>
<ul>
<li>{n}: exactamente n veces</li>
<li>{n,}: n o más veces</li>
<li>{,m}: a lo más m veces</li>
<li>{n,m}: entre n y m veces</li>
</ul>
<div class="sourceCode" id="cb349"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb349-1"><a href="tidyverse.html#cb349-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(x,<span class="st">&quot;X{3}&quot;</span>)</span></code></pre></div>
<div id="htmlwidget-c872195a89276dbbbd8d" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-c872195a89276dbbbd8d">{"x":{"html":"<ul>\n  <li>1888 es el año más largo en números romanos: MDCCCL<span class='match'>XXX<\/span>VIII<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<div class="sourceCode" id="cb350"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb350-1"><a href="tidyverse.html#cb350-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(x,<span class="st">&quot;X{1,2}&quot;</span>)</span></code></pre></div>
<div id="htmlwidget-67fce2845bc59302389b" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-67fce2845bc59302389b">{"x":{"html":"<ul>\n  <li>1888 es el año más largo en números romanos: MDCCCL<span class='match'>XX<\/span>XVIII<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<p><strong>Match múltiple / nulo</strong></p>
<p>Es interesante el siguiente ejemplo. ¿Qué es lo que sucede?</p>
<div class="sourceCode" id="cb351"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb351-1"><a href="tidyverse.html#cb351-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view</span>(x,<span class="st">&quot;M*&quot;</span>)</span></code></pre></div>
<div id="htmlwidget-d4d119f3546425fb1514" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-d4d119f3546425fb1514">{"x":{"html":"<ul>\n  <li><span class='match'><\/span>1888 es el año más largo en números romanos: MDCCCLXXXVIII<\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<p>Recordemos que los operadores * o ? busca un patrón que puede o no encontrarse dentro de la cadena de interés. En el caso anterior, la letra “M” puede o no encontrarse en la cadena “x.” En el ejemplo anterior, en cada posible caracter existe el hallazgo o no hallazgo de la letra “M,” de forma que el primer match que hace se encuentra al principio de la cadena. Una limitante de la función <em>str_view()</em> es que <strong>únicamente resalta la primer coincidencia</strong> encontrada con el patrón regular, sin embargo, la función <em>str_view_all()</em> se encarga de resaltar todas las coincidencias en la cadena, como se muestra a continuación.</p>
<div class="sourceCode" id="cb352"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb352-1"><a href="tidyverse.html#cb352-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_view_all</span>(x,<span class="st">&quot;M*&quot;</span>)</span></code></pre></div>
<div id="htmlwidget-eadd08074f3a04a072e2" style="width:960px;height:100%;" class="str_view html-widget"></div>
<script type="application/json" data-for="htmlwidget-eadd08074f3a04a072e2">{"x":{"html":"<ul>\n  <li><span class='match'><\/span>1<span class='match'><\/span>8<span class='match'><\/span>8<span class='match'><\/span>8<span class='match'><\/span> <span class='match'><\/span>e<span class='match'><\/span>s<span class='match'><\/span> <span class='match'><\/span>e<span class='match'><\/span>l<span class='match'><\/span> <span class='match'><\/span>a<span class='match'><\/span>ñ<span class='match'><\/span>o<span class='match'><\/span> <span class='match'><\/span>m<span class='match'><\/span>á<span class='match'><\/span>s<span class='match'><\/span> <span class='match'><\/span>l<span class='match'><\/span>a<span class='match'><\/span>r<span class='match'><\/span>g<span class='match'><\/span>o<span class='match'><\/span> <span class='match'><\/span>e<span class='match'><\/span>n<span class='match'><\/span> <span class='match'><\/span>n<span class='match'><\/span>ú<span class='match'><\/span>m<span class='match'><\/span>e<span class='match'><\/span>r<span class='match'><\/span>o<span class='match'><\/span>s<span class='match'><\/span> <span class='match'><\/span>r<span class='match'><\/span>o<span class='match'><\/span>m<span class='match'><\/span>a<span class='match'><\/span>n<span class='match'><\/span>o<span class='match'><\/span>s<span class='match'><\/span>:<span class='match'><\/span> <span class='match'>M<\/span><span class='match'><\/span>D<span class='match'><\/span>C<span class='match'><\/span>C<span class='match'><\/span>C<span class='match'><\/span>L<span class='match'><\/span>X<span class='match'><\/span>X<span class='match'><\/span>X<span class='match'><\/span>V<span class='match'><\/span>I<span class='match'><\/span>I<span class='match'><\/span>I<span class='match'><\/span><\/li>\n<\/ul>"},"evals":[],"jsHooks":[]}</script>
<p><strong>Herramientas</strong></p>
<p>Una vez que se han visto los aspectos básicos de las expresiones regulares, es posible utilizar los patrones coincidentes y combinarlos para aplicarlos en problemas reales. Algunas de las aplicaciones más comunes son:</p>
<ul>
<li>Determinar cuáles cadenas coinciden con un patrón.</li>
<li>Encontrar la posición de las coincidencias.</li>
<li>Extraer el contenido de las coincidencias.</li>
<li>Reemplazar coincidencias con nuevos valores.</li>
<li>Dividir una cadena basándose en una coincidencia.</li>
</ul>
<p>A continuación se analizarán las funciones que permitirán realizar las acciones anteriores.</p>
</div>
<div id="detectar-coincidencias" class="section level3" number="9.4.6">
<h3><span class="header-section-number">9.4.6</span> Detectar coincidencias</h3>
<p>Para determinar las cadenas de caracteres dentro de un vector que coinciden con un patrón, es posible utilizar la función <em>str_detect()</em>. La función regresará un vector booleano una vez que se introduzcan como argumentos el vector con cadenas y el patrón con el que se desea hacer la coincidencia.</p>
<p>Aplicando esta función a un marco de muestreo es posible apreciar si los elementos coinciden o no con algún patrón indicado.</p>
<p>En el siguiente ejemplo se puede apreciar cuáles frutas tienen entre sus letras una “a” o una “u.”</p>
<div class="sourceCode" id="cb353"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb353-1"><a href="tidyverse.html#cb353-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_detect</span>(fruit, <span class="st">&quot;[au]&quot;</span>)</span></code></pre></div>
<pre><code>##  [1]  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
## [13]  TRUE  TRUE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
## [25]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE
## [37] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE
## [49]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
## [61]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE
## [73]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE</code></pre>
<p>A continuación se puede apreciar una aplicación de la función <em>str_detect()</em>. Se usará el vector booleano para seleccionar el subconjunto del objeto <strong>fruit</strong> que tiene entre su nombre una letra “l” o una letra “o.”</p>
<div class="sourceCode" id="cb355"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb355-1"><a href="tidyverse.html#cb355-1" aria-hidden="true" tabindex="-1"></a>fruit[<span class="fu">str_detect</span>(fruit, <span class="st">&quot;[lo]&quot;</span>)]</span></code></pre></div>
<pre><code>##  [1] &quot;apple&quot;             &quot;apricot&quot;           &quot;avocado&quot;          
##  [4] &quot;bell pepper&quot;       &quot;bilberry&quot;          &quot;blackberry&quot;       
##  [7] &quot;blackcurrant&quot;      &quot;blood orange&quot;      &quot;blueberry&quot;        
## [10] &quot;boysenberry&quot;       &quot;canary melon&quot;      &quot;cantaloupe&quot;       
## [13] &quot;cherimoya&quot;         &quot;chili pepper&quot;      &quot;clementine&quot;       
## [16] &quot;cloudberry&quot;        &quot;coconut&quot;           &quot;damson&quot;           
## [19] &quot;dragonfruit&quot;       &quot;eggplant&quot;          &quot;elderberry&quot;       
## [22] &quot;feijoa&quot;            &quot;goji berry&quot;        &quot;gooseberry&quot;       
## [25] &quot;honeydew&quot;          &quot;huckleberry&quot;       &quot;jambul&quot;           
## [28] &quot;lemon&quot;             &quot;lime&quot;              &quot;loquat&quot;           
## [31] &quot;lychee&quot;            &quot;mango&quot;             &quot;mulberry&quot;         
## [34] &quot;olive&quot;             &quot;orange&quot;            &quot;pamelo&quot;           
## [37] &quot;passionfruit&quot;      &quot;persimmon&quot;         &quot;physalis&quot;         
## [40] &quot;pineapple&quot;         &quot;plum&quot;              &quot;pomegranate&quot;      
## [43] &quot;pomelo&quot;            &quot;purple mangosteen&quot; &quot;rock melon&quot;       
## [46] &quot;salal berry&quot;       &quot;tamarillo&quot;         &quot;ugli fruit&quot;       
## [49] &quot;watermelon&quot;</code></pre>
<p>De esta manera se va filtrando un marco muestral para quedarse únicamente con los elementos que coincidan con un patrón coincidente.</p>
</div>
<div id="contabilizar-coincidencias" class="section level3" number="9.4.7">
<h3><span class="header-section-number">9.4.7</span> Contabilizar coincidencias</h3>
<p>Una variación de la función anterior, es la función <em>str_count()</em>. Esta función en lugar de devolver un vector lógico, devuelve un vector de conteos que corresponde al número de veces que detectó una coincidencia para cada cadena dentro de un vector.</p>
<p>La manera de usarse es análoga a la función str_detect().</p>
<div class="sourceCode" id="cb357"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb357-1"><a href="tidyverse.html#cb357-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_count</span>(fruit, <span class="st">&quot;[aeiou]&quot;</span>)</span></code></pre></div>
<pre><code>##  [1] 2 3 4 3 3 2 2 3 5 3 3 4 4 5 4 1 4 4 3 3 2 3 2 2 2 4 3 2 3 4 1 3 4 2 4 3 3 3
## [39] 3 2 3 4 3 2 2 3 2 4 2 2 4 1 3 3 3 3 5 2 2 3 2 4 1 5 3 6 3 3 3 2 3 3 3 3 3 2
## [77] 4 4 4 4</code></pre>
<p>En el ejemplo anterior se puede apreciar el número de vocales que existen dentro de cada una de los nombres de las frutas.</p>
<p>Una de las aplicaciones más comunes para esta función, se encuentra en los estudios de análisis de textos. A continuación, se puede apreciar el promedio de vocales que son usadas dentro de los nombres de frutas en el objeto <strong>fruit</strong>.</p>
<div class="sourceCode" id="cb359"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb359-1"><a href="tidyverse.html#cb359-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">str_count</span>(fruit, <span class="st">&quot;[aeiou]&quot;</span>))</span></code></pre></div>
<pre><code>## [1] 3.0125</code></pre>
<p>Otro ejemplo más complejo de esta función y sus aplicaciones es el siguiente:</p>
<div class="sourceCode" id="cb361"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb361-1"><a href="tidyverse.html#cb361-1" aria-hidden="true" tabindex="-1"></a>tabla <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb361-2"><a href="tidyverse.html#cb361-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;Vocal&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;a&quot;</span>,<span class="st">&quot;e&quot;</span>,<span class="st">&quot;i&quot;</span>,<span class="st">&quot;o&quot;</span>,<span class="st">&quot;u&quot;</span>),</span>
<span id="cb361-3"><a href="tidyverse.html#cb361-3" aria-hidden="true" tabindex="-1"></a>  <span class="st">&quot;Conteos&quot;</span> <span class="ot">=</span> <span class="fu">c</span>(<span class="fu">sum</span>(<span class="fu">str_count</span>(fruit, <span class="st">&quot;a&quot;</span>)),<span class="fu">sum</span>(<span class="fu">str_count</span>(fruit, <span class="st">&quot;e&quot;</span>)),</span>
<span id="cb361-4"><a href="tidyverse.html#cb361-4" aria-hidden="true" tabindex="-1"></a>                <span class="fu">sum</span>(<span class="fu">str_count</span>(fruit, <span class="st">&quot;i&quot;</span>)),<span class="fu">sum</span>(<span class="fu">str_count</span>(fruit, <span class="st">&quot;o&quot;</span>)),</span>
<span id="cb361-5"><a href="tidyverse.html#cb361-5" aria-hidden="true" tabindex="-1"></a>                <span class="fu">sum</span>(<span class="fu">str_count</span>(fruit, <span class="st">&quot;u&quot;</span>)))</span>
<span id="cb361-6"><a href="tidyverse.html#cb361-6" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span> </span>
<span id="cb361-7"><a href="tidyverse.html#cb361-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Porcentaje =</span> Conteos<span class="sc">/</span><span class="fu">sum</span>(Conteos))</span>
<span id="cb361-8"><a href="tidyverse.html#cb361-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb361-9"><a href="tidyverse.html#cb361-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb361-10"><a href="tidyverse.html#cb361-10" aria-hidden="true" tabindex="-1"></a>tabla</span></code></pre></div>
<pre><code>##   Vocal Conteos Porcentaje
## 1     a      65  0.2697095
## 2     e      72  0.2987552
## 3     i      34  0.1410788
## 4     o      36  0.1493776
## 5     u      34  0.1410788</code></pre>
<p>De esta manera es posible visualizar los conteos totales que tuvo cada vocal. Se calculó el porcentaje de aparición que tiene cada vocal con respecto al total de vocales en el conjunto.</p>
<p>Un dato curioso que es posible concluir con este ejemplo, es que, las vocales “a” y “e” aparecen casi dos veces más que el resto de las vocales en el conjunto <strong>fruit</strong>.</p>
<p>El anterior es un ejemplo sencillo que tiene por objetivo ilustar el aprovechamiento de las funciones, sin embargo, una aplicación más robusta podría permitir que a través de los tweets emitidos a candidatos políticos, se realice un análisis de sentimientos, en el cual cada tweet sea asociado a uno o más sentimientos tales como: alegría, enojo, miedo, tristeza, adversión, etc.</p>
<p>Posteriormente, de manera análoga a los conteos de vocales con porcentajes, se podría analizar la distribución de los sentimientos asociados a las opiniones de cada uno de los candidatos políticos. Adicionalmente, se podría realizar un análisis en donde se muestren las palabras que más se repiten al expresarse de un candidato.</p>
</div>
<div id="extraer-coincidencias" class="section level3" number="9.4.8">
<h3><span class="header-section-number">9.4.8</span> Extraer coincidencias</h3>
<p>Cuando se desea identificar y extraer un subgrupo particular de elementos que cumplan con cierta condición definida a través de un patrón coincidente, la función <em>str_extract()</em> es la mejor opción para realizar esta tarea.</p>
<p>Si se desea extraer el subconjunto de sentencias conjuntivas o disyuntivas es necesario definir el patrón coincidente con el cuál se compararán las sentencias para ser extraídas.</p>
<div class="sourceCode" id="cb363"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb363-1"><a href="tidyverse.html#cb363-1" aria-hidden="true" tabindex="-1"></a>patron <span class="ot">&lt;-</span> <span class="st">&quot;( and )|( or )&quot;</span></span></code></pre></div>
<p>Por su traducción en inglés, “and” y “or” son los conectores “y” y “o” respectivamente. Primero se filtrarán las oraciones que cumplen con la condición de que las conjunciones “and” u “or” se encuentren dentro y posteriormente se extraerán los elementos coincidentes.</p>
<div class="sourceCode" id="cb364"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb364-1"><a href="tidyverse.html#cb364-1" aria-hidden="true" tabindex="-1"></a>coincidencias <span class="ot">&lt;-</span> <span class="fu">str_subset</span>(sentences, patron)</span>
<span id="cb364-2"><a href="tidyverse.html#cb364-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(coincidencias,<span class="dv">10</span>)</span></code></pre></div>
<pre><code>##  [1] &quot;The hogs were fed chopped corn and garbage.&quot;    
##  [2] &quot;Kick the ball straight and follow through.&quot;     
##  [3] &quot;Smoky fires lack flame and heat.&quot;               
##  [4] &quot;The fish twisted and turned on the bent hook.&quot;  
##  [5] &quot;Press the pants and sew a button on the vest.&quot;  
##  [6] &quot;The colt reared and threw the tall rider.&quot;      
##  [7] &quot;It snowed, rained, and hailed the same morning.&quot;
##  [8] &quot;The wrist was badly strained and hung limp.&quot;    
##  [9] &quot;Hop over the fence and plunge in.&quot;              
## [10] &quot;Cars and busses stalled in snow drifts.&quot;</code></pre>
<p>Apenas 123 sentencias cumplen con la condición. Éstas representan el 17.08% del total.
Para extraer los elementos coincidentes, la función <em>str_extract()</em> se usa de la siguiente manera:</p>
<div class="sourceCode" id="cb366"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb366-1"><a href="tidyverse.html#cb366-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_extract</span>(coincidencias, patron)</span></code></pre></div>
<pre><code>##   [1] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;
##  [10] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;
##  [19] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;
##  [28] &quot; and &quot; &quot; or &quot;  &quot; or &quot;  &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;
##  [37] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; or &quot;  &quot; and &quot; &quot; and &quot; &quot; and &quot;
##  [46] &quot; or &quot;  &quot; and &quot; &quot; or &quot;  &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;
##  [55] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;
##  [64] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;
##  [73] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;
##  [82] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; or &quot;  &quot; and &quot; &quot; and &quot; &quot; or &quot; 
##  [91] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;
## [100] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; or &quot;  &quot; and &quot; &quot; and &quot;
## [109] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;
## [118] &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot; &quot; and &quot;</code></pre>
<p>Con el código anterior se logra extraer el patrón coincidente de cada una de las sentencias, sin embargo, sólo se logra extraer la primer coincidencia de cada cadena en donde hubo al menos una coincidencia. Para extender este resultado a todos los patrones coincidentes dentro de la sentencia, se debe agregar el sufijo "_all" a la función. La función <em>str_extract_all()</em> extraerá todas las coincidencias y las agrupará en un objeto cuya estructura será la de una “lista.” Con la función <em>head()</em> se logrará visualizar los 5 primeros elementos de la lista que guarda el resultado generado por la función <em>str_extract_all()</em>.</p>
<div class="sourceCode" id="cb368"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb368-1"><a href="tidyverse.html#cb368-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="fu">str_extract_all</span>(coincidencias,patron), <span class="dv">5</span>)</span></code></pre></div>
<pre><code>## [[1]]
## [1] &quot; and &quot;
## 
## [[2]]
## [1] &quot; and &quot;
## 
## [[3]]
## [1] &quot; and &quot;
## 
## [[4]]
## [1] &quot; and &quot;
## 
## [[5]]
## [1] &quot; and &quot;</code></pre>
<p>Un formato más compacto del resultado anterior se logra al agregar el parámetro “simplfy = TRUE” dentro de la función de extracción. Para visualizar aleatoriamente diez de los resultados generados, se puede hacer uso de la función <em>sample_n()</em> de la librería <em>dplyr</em>.</p>
<div class="sourceCode" id="cb370"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb370-1"><a href="tidyverse.html#cb370-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">sample_n</span>(</span>
<span id="cb370-2"><a href="tidyverse.html#cb370-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">tbl =</span> <span class="fu">as_tibble</span>(<span class="fu">str_extract_all</span>(coincidencias, patron, <span class="at">simplify =</span> <span class="cn">TRUE</span>), <span class="at">.name_repair =</span> <span class="st">&quot;unique&quot;</span>), </span>
<span id="cb370-3"><a href="tidyverse.html#cb370-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">size =</span> <span class="dv">10</span></span>
<span id="cb370-4"><a href="tidyverse.html#cb370-4" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<pre><code>## # A tibble: 10 × 2
##    ...1    ...2   
##    &lt;chr&gt;   &lt;chr&gt;  
##  1 &quot; and &quot; &quot;&quot;     
##  2 &quot; and &quot; &quot;&quot;     
##  3 &quot; and &quot; &quot;&quot;     
##  4 &quot; and &quot; &quot;&quot;     
##  5 &quot; and &quot; &quot;&quot;     
##  6 &quot; and &quot; &quot;&quot;     
##  7 &quot; and &quot; &quot; and &quot;
##  8 &quot; and &quot; &quot;&quot;     
##  9 &quot; and &quot; &quot;&quot;     
## 10 &quot; and &quot; &quot;&quot;</code></pre>
<p>Si en alguna cadena existieran más de dos patrones coincidentes, aparecería en la segunda columna el patrón encontrado (e.g., elemento en el séptimo renglón), de lo contrario, el elemento de la segunda columna permanecerá vacío a través de dos comillas.</p>
<p>El resultado será un objeto de la clase <em>data.frame</em> que tendrá tantas columnas como coincidencias máximas hayan existido en una sentencia.</p>
<p>La siguientes línea de código permite hacer conteos del número de veces que el patrón coincidente fue detectado en el vector de oraciones. La función <em>str_count()</em> indicará el número de veces que el patrón fue detectado en cada oración. Finalmente, el vector numérico se suma.</p>
<div class="sourceCode" id="cb372"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb372-1"><a href="tidyverse.html#cb372-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(<span class="fu">str_count</span>(coincidencias, <span class="at">pattern =</span> patron))</span></code></pre></div>
<pre><code>## [1] 126</code></pre>
<p>Con este dato, se puede decir que a lo largo de 123 oraciones, se puede encontrar 126 veces el patrón indicado. Este tipo de análisis nos permite hacer reportes como el siguiente: En promedio, cada oración tiene incluido 1.02 veces el patrón coincidente.</p>
<p>A continuación, se revisará el modo de detectar y reemplazar patrones regulares.</p>
</div>
<div id="reemplazar-coincidencias" class="section level3" number="9.4.9">
<h3><span class="header-section-number">9.4.9</span> Reemplazar coincidencias</h3>
<p>A menudo es necesario reemplazar algunos patrones. Ya sea derivado de un error en las cadenas de texto o por interés de presentar los resultados de una manera distinta, identificar y sustituir un subconjunto de caracteres es algo que la función <em>str_replace()</em> de la paquetería stringr puede hacer.</p>
<p>Como todas las funciones vistas hasta el momento provenientes de la paquetería stringr, la función <em>str_replace()</em> recibe el objeto con las cadenas de caracteres originales y a través de un patrón de texto se hace la búsqueda de las coincidencias. Es posible incluir más de 1 patrón y asignar el nuevo texto que sustituirá al anterior para cada uno de los patrones definidos. La función <em>str_replace()</em> hará la sustitución de un solo patrón coincidente y la función <em>str_replace_all()</em> lo hará para todos los patrones definidos.</p>
<div class="sourceCode" id="cb374"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb374-1"><a href="tidyverse.html#cb374-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ejemplos de cambio de codigos a palabras o invertido  </span></span>
<span id="cb374-2"><a href="tidyverse.html#cb374-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb374-3"><a href="tidyverse.html#cb374-3" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;1&quot;</span>,<span class="st">&quot;2&quot;</span>,<span class="st">&quot;1&quot;</span>,<span class="st">&quot;2&quot;</span>,<span class="st">&quot;1&quot;</span>,<span class="st">&quot;2&quot;</span>,<span class="st">&quot;1&quot;</span>,<span class="st">&quot;2&quot;</span>,<span class="st">&quot;1&quot;</span>,<span class="st">&quot;2&quot;</span>)</span>
<span id="cb374-4"><a href="tidyverse.html#cb374-4" aria-hidden="true" tabindex="-1"></a>x1 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(x, <span class="st">&quot;1&quot;</span>,<span class="st">&quot;Hombre&quot;</span>)</span>
<span id="cb374-5"><a href="tidyverse.html#cb374-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(x1)</span></code></pre></div>
<pre><code>##  [1] &quot;Hombre&quot; &quot;2&quot;      &quot;Hombre&quot; &quot;2&quot;      &quot;Hombre&quot; &quot;2&quot;      &quot;Hombre&quot; &quot;2&quot;     
##  [9] &quot;Hombre&quot; &quot;2&quot;</code></pre>
<div class="sourceCode" id="cb376"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb376-1"><a href="tidyverse.html#cb376-1" aria-hidden="true" tabindex="-1"></a>x2 <span class="ot">&lt;-</span> <span class="fu">str_replace</span>(x1, <span class="st">&quot;2&quot;</span>,<span class="st">&quot;Mujer&quot;</span>)</span>
<span id="cb376-2"><a href="tidyverse.html#cb376-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(x2)</span></code></pre></div>
<pre><code>##  [1] &quot;Hombre&quot; &quot;Mujer&quot;  &quot;Hombre&quot; &quot;Mujer&quot;  &quot;Hombre&quot; &quot;Mujer&quot;  &quot;Hombre&quot; &quot;Mujer&quot; 
##  [9] &quot;Hombre&quot; &quot;Mujer&quot;</code></pre>
<div class="sourceCode" id="cb378"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb378-1"><a href="tidyverse.html#cb378-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Es posible replicar el resultado en un solo paso mediante str_replace_all</span></span>
<span id="cb378-2"><a href="tidyverse.html#cb378-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb378-3"><a href="tidyverse.html#cb378-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str_replace_all</span>(x, <span class="fu">c</span>(<span class="st">&quot;1&quot;</span> <span class="ot">=</span> <span class="st">&quot;Hombre&quot;</span>, <span class="st">&quot;2&quot;</span> <span class="ot">=</span> <span class="st">&quot;Mujer&quot;</span>))</span></code></pre></div>
<pre><code>##  [1] &quot;Hombre&quot; &quot;Mujer&quot;  &quot;Hombre&quot; &quot;Mujer&quot;  &quot;Hombre&quot; &quot;Mujer&quot;  &quot;Hombre&quot; &quot;Mujer&quot; 
##  [9] &quot;Hombre&quot; &quot;Mujer&quot;</code></pre>
</div>
<div id="divisiones-mediante-patrones" class="section level3" number="9.4.10">
<h3><span class="header-section-number">9.4.10</span> Divisiones mediante patrones</h3>
<p>La información se presenta en diferentes formatos todo el tiempo. A veces cada variable tiene su propia columna, pero a veces la información está mezclada y es necesario dividirla a fin de trabajar mejor con ella.</p>
<p>Un caso recurrente en donde se presenta esta operación es con las fechas. El formato de una fecha a menudo se presenta como dd/mm/aaaa. Bajo este formato se puede encontrar tres datos en uno solo (día, mes y año). Para dividirlo, se podría utilizar el caracter “/” como patrón de coincidencia que permita dividir los datos en tres columnas separadas. Se debe agregar el parámetro “<em>simplify = T</em>” para poder simplificar los resultados y visualizarlos en un objeto <em>data.frame()</em>. La manera de hacerlo es la siguiente:</p>
<p>Primero se genera un vector con fechas</p>
<div class="sourceCode" id="cb380"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb380-1"><a href="tidyverse.html#cb380-1" aria-hidden="true" tabindex="-1"></a>fechas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;15/11/1991&quot;</span>,<span class="st">&quot;20/11/1981&quot;</span>,<span class="st">&quot;04/02/1966&quot;</span>,<span class="st">&quot;01/10/1958&quot;</span>,<span class="st">&quot;23/04/1992&quot;</span>);fechas</span></code></pre></div>
<pre><code>## [1] &quot;15/11/1991&quot; &quot;20/11/1981&quot; &quot;04/02/1966&quot; &quot;01/10/1958&quot; &quot;23/04/1992&quot;</code></pre>
<p>Ahora, se generan tres columnas, una para el campo “Día,” otra para el campo “Mes” y otra para “Año”</p>
<div class="sourceCode" id="cb382"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb382-1"><a href="tidyverse.html#cb382-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str_split</span>(<span class="at">string =</span> fechas,<span class="at">pattern =</span> <span class="st">&quot;/&quot;</span>,<span class="at">n =</span> <span class="dv">3</span>, <span class="at">simplify =</span> T) <span class="sc">%&gt;%</span> </span>
<span id="cb382-2"><a href="tidyverse.html#cb382-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb382-3"><a href="tidyverse.html#cb382-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">day =</span> V1, <span class="at">month =</span> V2, <span class="at">year =</span> V3)</span></code></pre></div>
<pre><code>## Warning: The `x` argument of `as_tibble.matrix()` must have unique column names if `.name_repair` is omitted as of tibble 2.0.0.
## Using compatibility `.name_repair`.</code></pre>
<pre><code>## # A tibble: 5 × 3
##   day   month year 
##   &lt;chr&gt; &lt;chr&gt; &lt;chr&gt;
## 1 15    11    1991 
## 2 20    11    1981 
## 3 04    02    1966 
## 4 01    10    1958 
## 5 23    04    1992</code></pre>
</div>
<div id="localización-de-coincidencias" class="section level3" number="9.4.11">
<h3><span class="header-section-number">9.4.11</span> Localización de coincidencias</h3>
<p>Para poder hacer operaciones con algunas cadenas de caracteres, en ocasiones es necesario proporcionar los índices que denotan el inicio y el término de algún patrón de caracteres. La función <em>str_locate()</em> devuelve dichos índices una vez que se le haya proporcionado como argumento el patrón coincidente y el vector de cadenas de texto.</p>
<div class="sourceCode" id="cb385"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb385-1"><a href="tidyverse.html#cb385-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;090020001-123&quot;</span>,<span class="st">&quot;090001-512&quot;</span>,<span class="st">&quot;09002-1236&quot;</span>,<span class="st">&quot;90020001-1237&quot;</span>,<span class="st">&quot;09001-123811&quot;</span>)</span>
<span id="cb385-2"><a href="tidyverse.html#cb385-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str_locate</span>(x,<span class="st">&quot;-</span><span class="sc">\\</span><span class="st">d{2,}&quot;</span>)</span></code></pre></div>
<pre><code>##      start end
## [1,]    10  13
## [2,]     7  10
## [3,]     6  10
## [4,]     9  13
## [5,]     6  12</code></pre>
<p>El ejemplo anterior muestra la manera en la que se localizan los índices iniciales y finales de los caracteres posteriores al símbolo “-,” que cumplan con tener al menos 2 dígitos. Hay que tomar en cuenta que bajo esta forma de extraer los índices, la posición del caracter “-” está incluida y es ahí donde inicia el conteo.</p>
<p>Habiendo platicado de esto, podemos hablar de uno de los temas importantes en muchas ocasiones complejos de la manipulación de datos… las fechas.</p>
</div>
</div>
<div id="manipulación-de-fechas-y-horas" class="section level2" number="9.5">
<h2><span class="header-section-number">9.5</span> Manipulación de fechas y horas</h2>
<div id="lectura-y-creación-de-datos-temporales" class="section level3" number="9.5.1">
<h3><span class="header-section-number">9.5.1</span> Lectura y creación de datos temporales</h3>
<p>Una de la tareas más comunes en el análisis de datos es la manipulación de fechas y horas. Existe una infinidad de situaciones en donde saber operar con esta clase de datos es vital para el análisis de datos general. El primer paso es lograr identificar una cadena de caracteres como un dato temporal. Veamos un primer ejemplo:</p>
<div class="sourceCode" id="cb387"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb387-1"><a href="tidyverse.html#cb387-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lubridate)</span>
<span id="cb387-2"><a href="tidyverse.html#cb387-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb387-3"><a href="tidyverse.html#cb387-3" aria-hidden="true" tabindex="-1"></a>fechas <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;2018/09/11&quot;</span>, <span class="st">&quot;1992/04/23&quot;</span>, <span class="st">&quot;1966/02/04&quot;</span>, <span class="st">&quot;1958/10/01&quot;</span>, <span class="st">&quot;1991/11/15&quot;</span>)</span>
<span id="cb387-4"><a href="tidyverse.html#cb387-4" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(fechas)</span></code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<div class="sourceCode" id="cb389"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb389-1"><a href="tidyverse.html#cb389-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(<span class="fu">as_date</span>(fechas))</span></code></pre></div>
<pre><code>## [1] &quot;Date&quot;</code></pre>
<p>Como puede apreciarse, los elementos del vector ahora son de la clase “Date.” La función <em>as_date()</em> transforma caracteres a fechas. Otra forma de realizar la implementación de datos temporales es directamente la creación de datos temporales a través de las funciones <em>make_date()</em> y <em>make_datetime()</em>. Esta función recibe los parámetros de cada unidad temporal y crea el dato adecuado para representarlo, ya sea <em>date</em> o <em>datetime</em>.</p>
<div class="sourceCode" id="cb391"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb391-1"><a href="tidyverse.html#cb391-1" aria-hidden="true" tabindex="-1"></a><span class="fu">make_date</span>(<span class="at">year =</span> <span class="dv">1999</span>, <span class="at">month =</span> <span class="dv">06</span>, <span class="at">day =</span> <span class="dv">16</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1999-06-16&quot;</code></pre>
<div class="sourceCode" id="cb393"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb393-1"><a href="tidyverse.html#cb393-1" aria-hidden="true" tabindex="-1"></a><span class="fu">make_datetime</span>(<span class="at">year =</span> <span class="dv">1999</span><span class="sc">:</span><span class="dv">2001</span>, <span class="at">month =</span> <span class="dv">06</span>, <span class="at">day =</span> <span class="dv">16</span>, <span class="at">hour =</span> <span class="dv">10</span><span class="sc">:</span><span class="dv">12</span>, <span class="at">min =</span> <span class="dv">37</span>, <span class="at">sec =</span> <span class="dv">15</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1999-06-16 10:37:15 UTC&quot; &quot;2000-06-16 11:37:15 UTC&quot;
## [3] &quot;2001-06-16 12:37:15 UTC&quot;</code></pre>
<p>El segundo ejemplo muestra la capacidad de estas funciones para crear una secuencia de fechas a partir de vectores de cada posible unidad temporal (día, mes año, hora, etc)</p>
<p>Algo que puede apreciarse en los ejemplos anteriores y que es necesario mencionar, es que el formato universal de fecha se escribe: <strong>yyyy/mm/dd</strong>. En países como USA el formato es <strong>mm/dd/yyyy</strong> y en México y otras partes del mundo puede escribirse comunmente <strong>dd/mm/yyyy</strong>. Este tipo de diferencia a veces puede llegar a generar confusión sobre la fecha exacta en cuestión, más aún si se abrevia el año a dos caracteres <strong>yy</strong>.</p>
<p>La librería <strong>lubridate</strong> ofrece funciones para lidiar con el formato de lectura. Estas funciones son:</p>
<ul>
<li><p>dmy / dmy_h / dmy_hm / dmy_hms</p></li>
<li><p>mdy / mdy_h / mdy_hm / mdy_hms</p></li>
<li><p>ymd / ymd_h / ymd_hm / ymd_hms</p></li>
<li><p>hm / hms</p></li>
</ul>
<p>Con todas las funciones mencionadas anteriormente se puede leer cualquier cadena de caracteres que contenga el formato especificado. A continuación, un ejemplo:</p>
<div class="sourceCode" id="cb395"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb395-1"><a href="tidyverse.html#cb395-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mdy</span>(<span class="st">&quot;11/25/1982&quot;</span>)</span></code></pre></div>
<pre><code>## [1] &quot;1982-11-25&quot;</code></pre>
<p>Automáticamente cualquiera de las funciones antes mencionadas transforma el formato específico al formato universal.</p>
</div>
<div id="extracción-de-datos-temporales" class="section level3" number="9.5.2">
<h3><span class="header-section-number">9.5.2</span> Extracción de datos temporales</h3>
<p>Una vez que los datos temporales ya se encuentran creados, es importante saber la manera de extraer información particular de nuestro interés. En esta sección se revisará la manera de extraer cualquier unidad temporal a partir de una cadena completa de caracteres. a través de lubridate, las funciones para extracción de sub unidades temporales son intuitivas.</p>
<div class="sourceCode" id="cb397"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb397-1"><a href="tidyverse.html#cb397-1" aria-hidden="true" tabindex="-1"></a>tiempo <span class="ot">&lt;-</span> <span class="fu">make_datetime</span>(<span class="at">year =</span> <span class="dv">2004</span>, <span class="at">month =</span> <span class="dv">9</span>, <span class="at">day =</span> <span class="dv">25</span>, <span class="at">hour =</span> <span class="dv">11</span>, <span class="at">min =</span> <span class="dv">30</span>, <span class="at">sec =</span> <span class="dv">1</span>)</span>
<span id="cb397-2"><a href="tidyverse.html#cb397-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb397-3"><a href="tidyverse.html#cb397-3" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">year</span>(tiempo)</span></code></pre></div>
<pre><code>## [1] 2004</code></pre>
<div class="sourceCode" id="cb399"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb399-1"><a href="tidyverse.html#cb399-1" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">month</span>(tiempo)</span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<div class="sourceCode" id="cb401"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb401-1"><a href="tidyverse.html#cb401-1" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">month</span>(tiempo, <span class="at">label =</span> T, <span class="at">abbr =</span> F)</span></code></pre></div>
<pre><code>## [1] septiembre
## 12 Levels: enero &lt; febrero &lt; marzo &lt; abril &lt; mayo &lt; junio &lt; ... &lt; diciembre</code></pre>
<div class="sourceCode" id="cb403"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb403-1"><a href="tidyverse.html#cb403-1" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">day</span>(tiempo)</span></code></pre></div>
<pre><code>## [1] 25</code></pre>
<div class="sourceCode" id="cb405"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb405-1"><a href="tidyverse.html#cb405-1" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">hour</span>(tiempo)</span></code></pre></div>
<pre><code>## [1] 11</code></pre>
<div class="sourceCode" id="cb407"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb407-1"><a href="tidyverse.html#cb407-1" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">minute</span>(tiempo)</span></code></pre></div>
<pre><code>## [1] 30</code></pre>
<div class="sourceCode" id="cb409"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb409-1"><a href="tidyverse.html#cb409-1" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">second</span>(tiempo)</span></code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>Después de las unidades temporales básicas, es posible también extraer día de la semana o día del mes, si es de interés.</p>
<div class="sourceCode" id="cb411"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb411-1"><a href="tidyverse.html#cb411-1" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">wday</span>(tiempo)</span></code></pre></div>
<pre><code>## [1] 7</code></pre>
<div class="sourceCode" id="cb413"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb413-1"><a href="tidyverse.html#cb413-1" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">wday</span>(tiempo, <span class="at">label =</span> T, <span class="at">abbr =</span> F)</span></code></pre></div>
<pre><code>## [1] sábado
## 7 Levels: domingo &lt; lunes &lt; martes &lt; miércoles &lt; jueves &lt; ... &lt; sábado</code></pre>
<div class="sourceCode" id="cb415"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb415-1"><a href="tidyverse.html#cb415-1" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">mday</span>(tiempo)</span></code></pre></div>
<pre><code>## [1] 25</code></pre>
<div class="sourceCode" id="cb417"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb417-1"><a href="tidyverse.html#cb417-1" aria-hidden="true" tabindex="-1"></a>lubridate<span class="sc">::</span><span class="fu">yday</span>(tiempo)</span></code></pre></div>
<pre><code>## [1] 269</code></pre>
</div>
<div id="operaciones-temporales" class="section level3" number="9.5.3">
<h3><span class="header-section-number">9.5.3</span> Operaciones temporales</h3>
<p>Las operaciones aritméticas entre datos temporales es cotidiano en todo momento cuando se analizan datos. Operaciones de sumas y restas de fechas y horas que permiten conocer la longitud de tiempo en dos momentos es una tarea que puede resolverse a través de los operadores aritméticos y lógicos.</p>
<p>Resta entre fechas</p>
<div class="sourceCode" id="cb419"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb419-1"><a href="tidyverse.html#cb419-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as_date</span>(<span class="st">&quot;1991/11/15&quot;</span>) <span class="sc">-</span> <span class="fu">as_date</span>(<span class="st">&quot;1992/04/23&quot;</span>)</span></code></pre></div>
<pre><code>## Time difference of -160 days</code></pre>
<div class="sourceCode" id="cb421"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb421-1"><a href="tidyverse.html#cb421-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as_date</span>(<span class="st">&quot;1992/04/23&quot;</span>) <span class="sc">-</span> <span class="fu">as_date</span>(<span class="st">&quot;1991/11/15&quot;</span>)</span></code></pre></div>
<pre><code>## Time difference of 160 days</code></pre>
<p>Suma y resta de días</p>
<div class="sourceCode" id="cb423"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb423-1"><a href="tidyverse.html#cb423-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as_date</span>(<span class="st">&quot;1991/11/15&quot;</span>) <span class="sc">+</span> <span class="dv">365</span></span></code></pre></div>
<pre><code>## [1] &quot;1992-11-14&quot;</code></pre>
<p>Operadores lógicos</p>
<div class="sourceCode" id="cb425"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb425-1"><a href="tidyverse.html#cb425-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as_date</span>(<span class="st">&quot;1992/04/23&quot;</span>) <span class="sc">&gt;</span> <span class="fu">as_date</span>(<span class="st">&quot;1991/11/15&quot;</span>)</span></code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<div class="sourceCode" id="cb427"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb427-1"><a href="tidyverse.html#cb427-1" aria-hidden="true" tabindex="-1"></a><span class="fu">as_date</span>(<span class="st">&quot;1992/04/23&quot;</span>) <span class="sc">&lt;</span> <span class="fu">as_date</span>(<span class="st">&quot;1991/11/15&quot;</span>)</span></code></pre></div>
<pre><code>## [1] FALSE</code></pre>
<p>Cada una de las operaciones vistas en este capítulo son compatibles con dplyr y el resto de las librerías tidyverse.</p>

</div>
</div>
</div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>

$('.pipehover_incremental tr').hover(function() {
  $(this).removeClass()
  $(this).prevAll().removeClass()
  $(this).nextAll().removeClass()
  $(this).addClass('hover');
  $(this).prevAll().addClass('hover');
  $(this).closest('div').next().find('img').attr("src", $(this).attr("link"));
});


$('.pipehover_select_one_row tr').hover(function() {
  $(this).removeClass()
  $(this).prevAll().removeClass()
  $(this).nextAll().removeClass()
  $(this).addClass('hover');
  $(this).closest('div').next().find('img').attr("src", $(this).attr("link"));
});

</script>
            </section>

          </div>
        </div>
      </div>
<a href="lectura-de-datos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ggplot.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["Introducción a Ciencia de Datos con R (Tidyverse).pdf"],
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
